export const dict = [
  ["har du haft ringet", "har .*haft ringet", "Generelt", "Slet 'haft'", 1, 1, 1],
  ["på den korte bane", "(korte|lange) bane", "Kliche", "Erstat med original vending", 1, 1, 1],
  ["satelit", "satelit", "Stavefejl", "satelit -> satellit", 1, 1, 1],
  ["forgodtbefindene", "forgodtbefindene", "Stavefejl", "forgodtbefindene -> forgodtbefindende", 1, 1, 1],
  ["ekvivalent", "ekvivalent", "Stavefejl", "ekvivalent -> ækvivalent", 1, 1, 1],
  ["tovholder", "tovholder", "Kliche", "Erstat med original vending", 1, 1, 1],
  ["været i tårer", "(været?|er|var) i tårer", "Anglicisme", "Fra det engelske udtryk 'was in tears'", 1, 1, 1],
  ["gå efter manden", "(gå(r|et)?|gik) efter manden", "Kliche", "Erstat med original vending", 1, 1, 1],
  ["statuserne", "statuserne", "Stavefejl", "statuserne -> statusserne", 1, 1, 1],
  ["postfaktuel", "postfaktuelt?", "Generelt", "Mener du 'løgn'?", 1, 1, 0],
  ["sms-besked", "sms-besked|(sms besked)", "Dobbeltkonfekt", "SMS", 1, 1, 1],
  ["istand", "istand", "Stavefejl", "istand -> i stand", 1, 1, 1],
  ["triologi", "triologi", "Stavefejl", "triologi -> trilogi", 1, 1, 1],
  [
    "springe over, hvor gærdet er lavest",
    "(springer?|sprunget|sprang) over,? hvor gærdet (er|var) (lav(t|est)?)",
    "Kliche",
    "Erstat med original vending",
    1,
    1,
    1,
  ],
  ["sparekniv", "sparekniv", "Kliche", "Erstat med original vending", 1, 1, 1],
  ["gletscher", "gletscher", "Stavefejl", "gletscher -> gletsjer", 1, 1, 1],
  ["Tage aktion", "((tage(r|t)?)|tog) aktion", "Anglicisme", "Fra det engelske udtryk 'to take action on'", 1, 1, 1],
  ["ligger i kortene", "(ligge(t|r)?|lå) i kortene", "Kliche", "Erstat med original vending", 1, 1, 1],
  ["russik", "russik", "Stavefejl", "russik -> russisk", 1, 1, 1],
  ["undertegnede", "undertegnede", "Formelt", "Kan du nøjes med at skrive 'mig' eller 'jeg'?", 1, 1, 1],
  ["ministerie", "ministerie", "Stavefejl", "ministerie -> ministerium", 1, 1, 1],
  ["omstændigt", "omstændigt", "Generelt", "omstændeligt", 1, 1, 1],
  ["våbentilstand", "våbentilstand", "Stavefejl", "våbentilstand -> våbenstilstand", 1, 1, 1],
  ["garnision", "garnision", "Stavefejl", "garnision -> garnison", 1, 1, 1],
  ["mega", "mega", "Fyldeord", "Overvej, om du kan slette eller omformulere", 1, 1, 1],
  ["bølgerne går højt", "bølgerne (går|gik) højt", "Kliche", "Erstat med original vending", 1, 1, 1],
  ["ummiddelbart", "ummiddelbart", "Stavefejl", "ummiddelbart -> umiddelbart", 1, 1, 1],
  ["publikumet", "publikumet", "Stavefejl", "publikumet -> publikummet", 1, 1, 1],
  ["hang ", "hang ", "Generelt", "hængte", 1, 1, 1],
  ["linier", "linier?", "Stavefejl", "linie -> linje", 1, 1, 1],
  ["tøjleløs", "tøjleløs", "Stavefejl", "tøjleløs -> tøjlesløs", 1, 1, 1],
  ["zealandsk", "zealandsk", "Stavefejl", "zealandsk -> newzealandsk", 1, 1, 1],
  [
    "indenfor",
    "indenfor(?!\\.)",
    "Grammatik",
    "Erstat med 'inden for'; Via DSN: I over 200 år har der været regler for om man skulle skrive den slags forbindelser i ét eller to ord. Reglerne har dog aldrig ligget fuldstændig fast. Oftest har hovedreglen været sådan at hvis de pågældende ord fungerede som præpositioner (hvis de altså havde en styrelse), skulle de skrives i to ord: den står inden for døren. Hvis de pågældende ord fungerede som adverbialer (hvis de ikke havde en styrelse), skulle de skrives i ét ord: den står indenfor.",
    0,
    1,
    1,
  ],
  ["Det er vidst", "det er vidst", "Generelt", "'vist' i stedet for 'vidst'", 1, 1, 1],
  ["Caraibien", "Caraibien", "Stavefejl", "Caraibien -> Caribien", 1, 1, 1],
  ["eksempelvist", "eksempelvist?", "Fyldeord", "Overvej, om du kan slette eller omformulere", 1, 1, 1],
  ["konstanterede", "konstanterede", "Stavefejl", "konstanterede -> konstaterede", 1, 1, 1],
  ["aftrykker", "aftrykker", "Stavefejl", "aftrykker -> aftrækker", 1, 1, 1],
  ["skredets", "skredets", "Stavefejl", "skredets -> skreddets", 1, 1, 1],
  ["budet", "budet", "Stavefejl", "budet -> buddet", 1, 1, 1],
  ["case", "case", "Anglicisme", "Bruges ofte på dansk, men erstat evt. med projekt", 1, 1, 1],
  ["prefikset", "prefikset", "Stavefejl", "prefikset -> præfikset", 1, 1, 1],
  ["ned ad bakke", "ned ad bakke", "Kliche", "Erstat med original vending", 1, 1, 1],
  [
    "gardenparty i haven",
    "gardenparty i haven?",
    "Dobbeltkonfekt",
    "Gardenpartys foregår per definition i haven",
    1,
    1,
    1,
  ],
  ["forene sig med", "forene(t|r|de)? sig med", "Generelt", "Man 'forliger' sig med noget", 1, 1, 1],
  [
    "italesætte",
    "(italesætte(r|de)?|italesat(te)?)",
    "Typisk anvendt forkert",
    "Erstat evt. med 'forklare' eller 'gøre rede for'",
    1,
    1,
    1,
  ],
  [
    "Ud over modbydelig",
    "ud ?over modbydeligt?",
    "Anglicisme",
    "Af det engelsk 'beyond repugnant'. På dansk hedder det 'mere end modbydeligt' eller 'ud over alle grænser modbydeligt'",
    1,
    1,
    1,
  ],
  ["Reminder", "reminder", "Anglicisme", "Erstattes med det danske ord 'påmindelse'", 1, 1, 1],
  ["ude og sige", "ude (og|at) (gøre|sige)", "Fyldeord", "Overvej, om du kan slette eller omformulere", 1, 1, 1],
  [
    "Udråbstegn (!)",
    "\\!",
    "Grammatik",
    "Vi har for vane at bruge mange udråbstegn i vores tekster! Det kan være OK(!), men overvej, om du kan pille nogle af dem ud!",
    1,
    1,
    1,
  ],
  ["byde ind med", "(byder?|budt|bød) ind med", "Dobbeltkonfekt", null, 1, 1, 1],
  [
    "Komme af krogen",
    "((komme(r|t)?)|kom) af krogen",
    "Anglicisme",
    "Fra det engelske udtryk 'get off the hook'",
    1,
    1,
    1,
  ],
  ["autencitet", "autencitet", "Stavefejl", "autencitet -> autenticitet", 1, 1, 1],
  ["Trådte op", "(træder?|trådte?) op", "Anglicisme", "Fra det engelske udtryk 'stepped up'", 1, 1, 1],
  ["faldgrubbe", "faldgrubbe", "Stavefejl", "faldgrubbe -> faldgrube", 1, 1, 1],
  ["imidlertid", "imidlertid", "Fyldeord", null, 1, 1, 1],
  ["despåagtet", "despåagtet", "Formelt", "Alt for formelt; desuden ikke et ord", 1, 1, 1],
  ["faldbyde", "faldbyde", "Stavefejl", "faldbyde -> falbyde", 1, 1, 1],
  ["ned af bakke", "ned af bakke", "Kliche", "Det er desuden ned 'ad' bakke", 1, 1, 1],
  ["fantastisk", "fantastisk", "Fyldeord", "Overvej, om du kan slette eller omformulere", 1, 1, 1],
  ["til fingerspidserne", "til fingerspidserne", "Kliche", "Erstat med original vending", 1, 1, 1],
  ["Cannada", "Cannada", "Stavefejl", "Cannada -> Canada", 1, 1, 1],
  ["spørsmål", "spørsmål", "Stavefejl", "spørsmål -> spørgsmål", 1, 1, 1],
  ["progromer", "progromer", "Stavefejl", "progromer -> pogromer", 1, 1, 1],
  ["hoved og hale", "hoved og hale", "Kliche", "Erstat med original vending", 1, 1, 1],
  ["kastanie", "kastanie", "Stavefejl", "kastanie -> kastanje", 1, 1, 1],
  ["sovjettisk", "sovjettisk", "Stavefejl", "sovjettisk -> sovjetisk", 1, 1, 1],
  ["i den henretning", "i den henretning", "Generelt", "i den henseende", 1, 1, 1],
  ["et gram salt", "et gram salt", "Generelt", "gran salt", 1, 1, 1],
  ["allerførst af alle", "allerførst af alle", "Dobbeltkonfekt", "Den giver lidt sig selv", 1, 1, 1],
  ["flamengo", "flamengo", "Stavefejl", "flamengo -> flamenco (sang, dans", 1, 1, 1],
  ["faktisk", "faktisk", "Fyldeord", "Overvej, om du kan slette eller omformulere", 1, 1, 1],
  ["sidde i rundkreds", "(sidder?|sad|være) i rundkreds", "Kliche", "Erstat med original vending", 1, 1, 1],
  ["tungen på vægtskålen", "tungen? på vægtskålen", "Kliche", "Erstat med original vending", 1, 1, 1],
  ["hjortvildt", "hjortvildt", "Stavefejl", "hjortvildt -> hjortevildt", 1, 1, 1],
  ["gå i rundkreds", "((gå(r|et)?)|gik) i rundkreds", "Kliche", "Erstat med original vending", 1, 1, 1],
  ["rigtigt", "rigtigt?", "Fyldeord", "Overvej, om du kan slette eller omformulere", 1, 1, 1],
  ["ligså", "ligså", "Stavefejl", "ligså -> lige så", 1, 1, 1],
  ["i forhold til", "i forhold til", "Typisk anvendt forkert", "Erstat evt. med 'for' eller 'til'", 1, 1, 1],
  ["skulptør", "skulptør", "Stavefejl", "skulptør -> hellere", 1, 1, 1],
  [
    "på en eller anden måde",
    "på en eller anden måde",
    "Fyldeord",
    "Overvej, om du kan slette eller omformulere",
    1,
    1,
    1,
  ],
  ["folketinget", "folketing(et)?", "Stavefejl", "folketinget -> Folketinget", 0, 1, 1],
  ["Når det kommer ned til", "kom(mer|met)? ned til", "Anglicisme", "Fra det engelske 'comes down to'", 1, 1, 1],
  ["samt", "samt", "Formelt", "samt -> og", 1, 1, 1],
  ["konstanterer", "konstanterer", "Stavefejl", "konstanterer -> konstaterer", 1, 1, 1],
  ["periferiske", "periferiske", "Stavefejl", "periferiske -> perifere", 1, 1, 1],
  ["hovedsaglig", "hovedsaglig", "Stavefejl", "hovedsaglig -> hovedsagelig", 1, 1, 1],
  ["Philippinerne", "Philippinerne", "Stavefejl", "Philippinerne -> Filippinerne", 1, 1, 1],
  [
    "vildt",
    "vildt?",
    "Fyldeord",
    "Medmindre du skriver om et vildt dyr, så er adjektivet 'vildt' ofte misbrugt som en unødvendig fortstærker,",
    1,
    1,
    1,
  ],
  ["rarieteter", "rarieteter", "Stavefejl", "rarieteter -> rariteter", 1, 1, 1],
  ["hoslagt fremsendes", "hoslagt fremsendes", "Formelt", "hoslagt fremsendes -> jeg vedhæfter", 1, 1, 1],
  ["skredet", "skredet", "Stavefejl", "skredet -> skreddet", 1, 1, 1],
  ["histografi", "histografi", "Stavefejl", "histografi -> historiografi", 1, 1, 1],
  [
    "hvad der kunne lægge bag",
    "hvad der (har|havde|kan|kunne) lægget? bag",
    "Generelt",
    "Skriv 'ligge' bag i stedet for 'lægge'",
    1,
    1,
    1,
  ],
  ["arbejdskollega", "arbejdskollega|arbejds-kollega", "Dobbeltkonfekt", "Kollega", 1, 1, 1],
  ["religionsudøvelse", "religionsudøvelse", "Stavefejl", "religionsudøvelse -> religionsøvelse", 1, 1, 1],
  ["ethiopisk", "ethiopisk", "Stavefejl", "ethiopisk -> etiopisk", 1, 1, 1],
  ["advokado", "advokado", "Stavefejl", "avokado", 1, 1, 1],
  [
    "i hendes/hans kontor",
    "i (hendes|hans) kontor",
    "Anglicisme",
    "Fra det engelske 'in his/her office'; erstat med 'på sit kontor'",
    1,
    1,
    1,
  ],
  ["aligne", "aligne(t|de|r)?", "Buzzword", "Buzzword; erstat evt. med 'nået til enighed om'", 1, 1, 1],
  ["barslet med", "barsle(r|de|t)? med", "Kliche", "Erstat med original vending", 1, 1, 1],
  ["billige priser", "billig(e)? pris(er)?", "Generelt", "Priser er lave, ikke billige", 1, 1, 1],
  ["penge hver", "(penge|kroner|værdi) hver", "Stavefejl", "Erstat 'hver' med 'værd'", 1, 1, 1],
  ["æstimat", "æstimat", "Stavefejl", "æstimat -> estimat", 1, 1, 1],
  ["deslige", "deslige", "Formelt", "Lidt for formelt", 1, 1, 1],
  ["filosofer", "filosofer", "Stavefejl", "filosofer -> filosoffer", 1, 1, 1],
  ["tilskuerepladsen", "tilskuerepladsen", "Stavefejl", "tilskuerepladsen -> tilskuerpladsen", 1, 1, 1],
  ["vanille", "vanille", "Stavefejl", "vanille -> vanilje", 1, 1, 1],
  ["kommite", "kommite", "Stavefejl", "kommite -> komité", 1, 1, 1],
  ["ombord", "ombord", "Stavefejl", "ombord -> om bord", 1, 1, 1],
  ["Guiseppe", "Guiseppe", "Stavefejl", "Guiseppe -> Giuseppe", 1, 1, 1],
  [
    "søge nye udfordringer",
    "søger? (jeg|du|han|hun|vi|de)? nye? udfordring(er)?",
    "Kliche",
    "En eufemiske for at blive fyret, der er brugt så ofte, at det nu er en kliche",
    1,
    1,
    1,
  ],
  ["små marginaler", "små marginaler", "Kliche", "Erstat med original vending", 1, 1, 1],
  ["skudets", "skudets", "Stavefejl", "skudets -> skuddets", 1, 1, 1],
  ["utrolig", "utroligt?", "Fyldeord", "Overvej, om du kan slette eller omformulere", 1, 1, 1],
  ["op af bakke", "op af bakke", "Kliche", "Det er desuden op 'ad' bakke", 1, 1, 1],
  ["kortene tæt til kroppen", "kort(ene)? tæt til kroppen", "Kliche", "Erstat med original vending", 1, 1, 1],
  ["albums", "albums", "Stavefejl", "albums -> albummer", 1, 1, 1],
  ["ordentlig overhaling", "ordentlig overhaling", "Kliche", "Erstat med original vending", 1, 1, 1],
  ["prefixer", "prefixer", "Stavefejl", "prefixer -> præfikser", 1, 1, 1],
  ["noglesinde", "noglesinde", "Stavefejl", "noglesinde -> nogensinde", 1, 1, 1],
  ["Bliv vænnet til det", "bliv vænnet til det", "Anglicisme", "Fra det engelske udtryk 'get used to it'", 1, 1, 1],
  ["foranledige", "foranledige(r|de|t)?", "Formelt", "foranledige -> sørge for", 1, 1, 1],
  ["erlægge", "erlægger?", "Formelt", "erlægge -> betale", 1, 1, 1],
  ["forholdsvist", "forholdsvist?", "Fyldeord", "Overvej, om du kan slette eller omformulere", 1, 1, 1],
  ["labratorie", "labratorie", "Stavefejl", "labratorie -> laboratorie eller laboratorium", 1, 1, 1],
  ["ærkebiskopsæde", "ærkebiskopsæde", "Stavefejl", "ærkebiskopsæde -> ærkebispesæde", 1, 1, 1],
  ["nok", "nok", "Fyldeord", "Overvej, om du kan slette eller omformulere", 1, 1, 1],
  ["vedrørende", "vedrørende", "Generelt", "Lidt for formelt", 1, 1, 1],
  ["linial", "linial", "Stavefejl", "linial -> lineal", 1, 1, 1],
  ["angiveligt ", "angiveligt?", "Fyldeord", "Overvej, om du kan slette eller omformulere", 1, 1, 1],
  ["dimision", "dimision", "Stavefejl", "dimision -> dimission, dimension", 1, 1, 1],
  ["Danebrog", "Danebrog", "Stavefejl", "Danebrog -> Dannebrog", 1, 1, 1],
  ["kom ind i kampen", "kom ind i kampen", "Kliche", "Erstat med original vending", 1, 1, 1],
  [
    "så tager vi den derfra",
    "så (tager|tog) vi (den|det) derfra ",
    "Anglicisme",
    "Fra det engelske 'We'll take it from there'; erstat med 'Det ser vi til den tid'",
    1,
    1,
    1,
  ],
  ["det nye sort", "det nye sort", "Kliche", "Erstat med original vending", 1, 1, 1],
  [
    "af den ene eller anden grund",
    "af ((den ene)|en) eller anden grund",
    "Fyldeord",
    "Overvej, om du kan slette eller omformulere",
    1,
    1,
    1,
  ],
  ["team", "team", "Anglicisme", "Bruges ofte på dansk, men erstat evt. med hold eller gruppe", 1, 1, 1],
  ["særlig", "særligt?", "Fyldeord", "Overvej, om du kan slette eller omformulere", 1, 1, 1],
  ["embalage", "embalage", "Stavefejl", "embalage -> emballage", 1, 1, 1],
  ["spis lige brød til", "spise? (lige)? brød til", "Kliche", "Erstat med original vending", 1, 1, 1],
  ["ryggrad", "ryggrad", "Stavefejl", "ryggrad -> rygrad", 1, 1, 1],
  ["herotisk", "herotisk", "Stavefejl", "herotisk -> heroisk, erotisk", 1, 1, 1],
  ["forbudet", "forbudet", "Stavefejl", "forbudet -> forbuddet", 1, 1, 1],
  ["zumbadans", "zumbadans|zumba-dans", "Dobbeltkonfekt", "Zumba *er* en dans", 1, 1, 1],
  ["neger", "neger", "Generelt", "Nej, nu er det altså slut med at bruge det ord", 1, 1, 1],
  ["udfra", "udfra", "Stavefejl", "udfra -> ud fra", 1, 1, 1],
  ["lidt", "lidt", "Fyldeord", "Overvej, om du kan slette eller omformulere", 1, 1, 1],
  ["liniere", "liniere", "Stavefejl", "liniere -> linjere", 1, 1, 1],
  ["vædsken", "vædsken", "Stavefejl", "vædsken -> væsken", 1, 1, 1],
  ["nobelprismodtager", "nobelprismodtager", "Stavefejl", "nobelprismodtager -> nobelpristager", 1, 1, 1],
  ["tøjleløst", "tøjleløst", "Stavefejl", "tøjleløst -> tøjlesløst", 1, 1, 1],
  ["chlorofyl", "chlorofyl", "Stavefejl", "chlorofyl -> klorofyl", 1, 1, 1],
  [
    "tilstede",
    "tilstede",
    "Stavefejl",
    "tilstede -> korrekt i betydningen 'tillade', men normalt menes 'til stede'",
    1,
    1,
    1,
  ],
  [
    "set med egne øjne",
    "set( det| den)? med( sine| dine| mine| ens| vores| jeres)?( egne)? Øjne",
    "Dobbeltkonfekt",
    "Selv set",
    1,
    1,
    1,
  ],
  ["overhovedet", "overhovedet", "Fyldeord", "Overvej, om du kan slette eller omformulere", 1, 1, 1],
  ["protokolen", "protokolen", "Stavefejl", "protokolen -> protokollen", 1, 1, 1],
  ["lang historie kort", "lang historie kort", "Kliche", "Erstat med original vending", 1, 1, 1],
  ["Storbritanien", "Storbritanien", "Stavefejl", "Storbritanien -> Storbritannien", 1, 1, 1],
  ["sportige", "sportige", "Stavefejl", "sportige -> sporty", 1, 1, 1],
  ["molekylarvægt", "molekylarvægt", "Stavefejl", "molekylarvægt -> molekylvægt", 1, 1, 1],
  ["accellererede", "accellererede", "Stavefejl", "accellererede -> accelererede", 1, 1, 1],
  ["smule", "smule", "Fyldeord", "Overvej, om du kan slette eller omformulere", 1, 1, 1],
  ["konstantere", "konstantere", "Stavefejl", "konstantere -> konstatere", 1, 1, 1],
  ["brædt", "brædt", "Stavefejl", "brædt -> bræt", 1, 1, 1],
  ["points", "points", "Stavefejl", "points -> point", 1, 1, 1],
  [
    "qua",
    "qua",
    "Formelt",
    "Folk, der bruger ordet 'qua' tror, at det får dem til at lyde kloge og akademiske. Det gør det ikke.",
    1,
    1,
    1,
  ],
  ["prefixet", "prefixet", "Stavefejl", "prefixet -> præfikset", 1, 1, 1],
  ["netop", "netop", "Fyldeord", "Overvej, om du kan slette eller omformulere", 1, 1, 1],
  ["forudrettet", "forudrette(t|de)", "Generelt", "forurettet uden 'd'", 1, 1, 1],
  [
    "fortærsket kliche",
    "fortærske(t|de) klich(é|e)(er)?",
    "Dobbeltkonfekt",
    "Klichéer er per definition fortærskede",
    1,
    1,
    1,
  ],
  ["jagtterminilogi", "jagtterminilogi", "Stavefejl", "jagtterminilogi -> jagtterminologi", 1, 1, 1],
  ["excl.", "excl\\.", "Stavefejl", "excl. -> ekskl.", 1, 1, 1],
  ["kommentere på", "kommentere(r|de|t)? på", "Dobbeltkonfekt", "Slet 'på'", 1, 1, 1],
  ["fredslutning", "fredslutning(en)?", "Stavefejl", "fredslutning -> fredsslutning", 1, 1, 1],
  ["svingeninger", "svingeninger", "Stavefejl", "svingeninger -> svingninger", 1, 1, 1],
  ["gletcher", "gletcher", "Stavefejl", "gletcher -> gletsjer", 1, 1, 1],
  ["nedstirre", "nedstirre", "Stavefejl", "nedstirre -> nidstirre", 1, 1, 1],
  ["sikkert", "sikkert", "Fyldeord", "Overvej, om du kan slette eller omformulere", 1, 1, 1],
  ["lykkedes", "lykkedes", "Generelt", "lykkes", 1, 1, 1],
  ["gå til fods", "(gå(r|et)?|gik) til fods", "Dobbeltkonfekt", "Den giver lidt sig selv", 1, 1, 1],
  [
    "søsætte et projekt",
    "(søsætter?|søsat(te)?) (projektet|(et projekt))",
    "Kliche",
    "Erstat med original vending",
    1,
    1,
    1,
  ],
  ["linierne", "linierne", "Stavefejl", "linierne -> linjerne", 1, 1, 1],
  ["parketten", "parketten", "Stavefejl", "parketten -> parkettet", 1, 1, 1],
  [
    "obducere et lig",
    "obducere(t|de|r)? ((et lig)|liget)",
    "Dobbeltkonfekt",
    "Det er underforstået, at der er tale om et lig",
    1,
    1,
    1,
  ],
  [
    "content",
    "content",
    "Anglicisme",
    "Bruges ofte på dansk, men erstat evt. med materiale, indhold eller tekst",
    1,
    1,
    1,
  ],
  ["slippe tøjlerne", "(slipper?|slap|sluppet) tøjlerne", "Kliche", "Erstat med original vending", 1, 1, 1],
  ["kokelev", "kokelev", "Stavefejl", "kokelev -> kokkeelev", 1, 1, 1],
  [
    "Overdrivelse forfremmer forståelsen",
    "Overdrivelse forfremmer forståelsen",
    "Generelt",
    "Overdrivelse fremmer forståelsen",
    1,
    1,
    1,
  ],
  ["meget ", "meget (?! lidt)", "Fyldeord", "Overvej, om du kan slette eller omformulere", 1, 1, 1],
  ["rarietet", "rarietet", "Stavefejl", "rarietet -> raritet", 1, 1, 1],
  ["virusser", "virusser", "Stavefejl", "virusser -> vira", 1, 1, 1],
  ["nød til", "nød til", "Stavefejl", "nød til -> nødt til", 1, 1, 1],
  ["gurillaen", "gurillaen", "Stavefejl", "gurillaen -> gorillaen, guerillaen", 1, 1, 1],
  [
    "mus-samtale",
    "(mus-samtale)|mussamtale",
    "Dobbeltkonfekt",
    "mus' er en forkortelse for 'medarbejdsudviklingssamtale'",
    1,
    1,
    1,
  ],
  ["cosmodrom", "cosmodrom(en)?", "Stavefejl", "cosmodrom -> kosmodrom", 1, 1, 1],
  ["hottentot", "hottentot", "Generelt", "Nej, nu er det altså slut med at bruge det ord.", 1, 1, 1],
  ["skure hunden mod hårene", "skure hunden mod hårene", "Generelt", "skue hunden på hårene", 1, 1, 1],
  ["sætte på hold", "sætte(r|t|de)? på hold", "Anglicisme", "Fra det engelske 'put on hold'; stille i bero", 1, 1, 1],
  ["som et led", "som et led", "Fyldeord", "Overvej, om du kan slette eller omformulere", 1, 1, 1],
  [
    "fordi, (komma efter fordi)",
    "fordi\\,\\s",
    "Grammatik",
    "Kan det være, at kommaet skal før 'fordi' (og ikke efter)?",
    1,
    1,
    1,
  ],
  ["genoptrykke", "genoptryk(ke|t|kte)", "Stavefejl", "genoptrykke -> optrykke (hvis ikke andet menes)", 1, 1, 1],
  ["gode råd vil være dyre", "gode råd vil være dyre", "Kliche", "Erstat med original vending", 1, 1, 1],
  ["påbegynde", "påbegynd(e|te|er)", "Formelt", "påbegynde -> begynde", 1, 1, 1],
  ["mandhjerte", "mandhjerte", "Stavefejl", "mandhjerte -> mandshjerte", 1, 1, 1],
  [
    "omkring",
    "omkring",
    "Typisk anvendt forkert",
    "Mange skriver 'omkring', hvor man egentligt burde skrive 'om'",
    1,
    1,
    1,
  ],
  ["rutsche", "rutsche", "Stavefejl", "rutsche -> rutsje", 1, 1, 1],
  ["super", "super", "Fyldeord", "Overvej, om du kan slette eller omformulere", 1, 1, 1],
  ["barrak", "barrak", "Stavefejl", "barrak -> barak", 1, 1, 1],
  ["artikeler", "artikeler", "Stavefejl", "artikeler -> artikler", 1, 1, 1],
  ["kirugi", "kirugi", "Stavefejl", "kirugi -> kirurgi", 1, 1, 1],
  [
    "opprioritere",
    "opprioritere(r|e|de)?",
    "Dobbeltkonfekt",
    "Det er underforstået, at prioritering er i opadgående retning",
    1,
    1,
    1,
  ],
  ["lodent", "lodent", "Stavefejl", "lodent -> loddent", 1, 1, 1],
  ["virkefeldt", "virkefeldt", "Stavefejl", "virkefeldt -> virkefelt", 1, 1, 1],
  ["kromosomantal", "kromosomantal", "Stavefejl", "kromosomantal -> kromosomtal", 1, 1, 1],
  ["es i ærme", "es i ærme", "Kliche", "Erstat med original vending", 1, 1, 1],
  ["ræsonere", "ræsonere", "Stavefejl", "ræsonere -> ræsonnere", 1, 1, 1],
  ["paranteser", "paranteser", "Stavefejl", "paranteser -> parenteser", 1, 1, 1],
  [
    "roterende fis i hornlygten",
    "roterende fis i hornlygten",
    "Generelt",
    "Roterende fis i kasketten/ Fis i en hornlygte",
    1,
    1,
    1,
  ],
  ["harcellere", "harcellere", "Stavefejl", "harcellere -> harcelere", 1, 1, 1],
  ["skelning", "skelning", "Stavefejl", "skelning -> skelen", 1, 1, 1],
  ["erimitage", "erimitagen?", "Stavefejl", "erimitage -> eremitage", 1, 1, 1],
  ["skudenes", "skudenes", "Stavefejl", "skudenes -> skuddenes", 1, 1, 1],
  ["Pensylvania", "Pensylvania", "Stavefejl", "Pensylvania -> Pennsylvania", 1, 1, 1],
  ["delegat", "delegat", "Stavefejl", "delegat -> delegeret", 1, 1, 1],
  ["annoncere", "annoncere(r|de|t)?", "Anglicisme", "Fra det engelske 'to announce'; erstat med 'meddele'", 1, 1, 1],
  [
    "den så du ikke lige komme",
    "(den|det) så (jeg|du|han|hun|vi|de) ikke (lige)? komme",
    "Kliche",
    "Erstat med original vending",
    1,
    1,
    1,
  ],
  ["tør vove", "tør( at)? vove", "Dobbeltkonfekt", "Et af ordene kan slettes, uden at betydningen mistes", 1, 1, 1],
  ["jægerfly", "jægerfly", "Stavefejl", "jægerfly -> jagerfly", 1, 1, 1],
  ["den hvide drik", "den hvide drik", "Kliche", "Erstat med original vending", 1, 1, 1],
  ["støtte op", "støtte(r|de|t)? op", "Dobbeltkonfekt", "støtte", 1, 1, 1],
  [
    "Gå ens vej",
    "(gå(r|et|r)?) .*(hans|hendes|ens|deres|jeres|min|din|vores) vej",
    "Anglicisme",
    "Fra det engelske udtryk 'go one's way'",
    1,
    1,
    1,
  ],
  ["Sachen", "Sachen", "Stavefejl", "Sachen -> Sachsen", 1, 1, 1],
  ["erhvers", "erhvers", "Stavefejl", "erhvers -> erhvervs", 1, 1, 1],
  ["fik sig et godt grin", "(få|fik) sig et godt grin", "Kliche", "Erstat med original vending", 1, 1, 1],
  ["kan man sige", "(kan|kunne) man sige", "Generelt", null, 1, 1, 1],
  ["fiktiv roman", "fiktive? roman(er)?", "Dobbeltkonfekt", "Alle romaner er fiktive", 1, 1, 1],
  ["komnikasjonssatlit", "komnikasjonssatlit", "Stavefejl", "komnikasjonssatlit -> kommunikationssatellit", 1, 1, 1],
  ["al", "al(?! tekst)", "Fyldeord", "Overvej, om du kan slette eller omformulere", 1, 1, 1],
  ["anmode om", "anmode(r|t|de)? om", "Formelt", "anmode om -> bede om, spørge om", 1, 1, 1],
  ["prefiks", "prefiks", "Stavefejl", "prefiks -> præfiks", 1, 1, 1],
  ["illyrianske", "illyrianske", "Stavefejl", "illyrianske -> illyriske", 1, 1, 1],
  ["element", "element(er|et)?", "Stavefejl", "element -> grundstof (når ikke andet menes)", 1, 1, 1],
  ["tyggummi", "tyggummi", "Stavefejl", "tyggummi -> tyggegummi", 1, 1, 1],
  ["psykriater", "psykriater", "Stavefejl", "psykriater -> psykiater", 1, 1, 1],
  [
    "opstart",
    "opstart",
    "Kliche",
    "Ikke kun er det en kliché, men det er også værd at tænke over, at der ikke findes en 'nedstart'",
    1,
    1,
    1,
  ],
  [
    "det hvide ud af lommerne",
    "det hvide ud af lommerne",
    "Generelt",
    "Det koster det hvide ud af øjnene/ At have lommerne fulde af penge",
    1,
    1,
    1,
  ],
  ["fibere", "fibere", "Stavefejl", "fibere -> fibre", 1, 1, 1],
  ["Afganistan", "Afganistan", "Stavefejl", "Afganistan -> Afghanistan", 1, 1, 1],
  ["skud fra hoften", "skud fra hoften", "Kliche", "Fodboldmetaforer er de værste af alle klichéer", 1, 1, 1],
  [
    "skruen oven vande",
    "skruen oven vande",
    "Generelt",
    "Vi skal holde skruen i vandet/ Vi skal holde hovedet oven vande",
    1,
    1,
    1,
  ],
  ["friluftsmuseet", "friluftsmuseet", "Stavefejl", "friluftsmuseet -> frilandsmuseet", 1, 1, 1],
  ["reperere", "reperere", "Stavefejl", "reperere -> reparere", 1, 1, 1],
  ["postbudde", "postbudde", "Stavefejl", "postbudde -> postbude", 1, 1, 1],
  ["en en", "en en", "Stavefejl", "Har du skrevet 'en' en gang for meget?", 1, 1, 1],
  ["lærne", "lærne", "Stavefejl", "lærne -> lærerne, læren", 1, 1, 1],
  [
    "evidens",
    "evidens",
    "Typisk anvendt forkert",
    "Betyder ikke bevis, men det umiddelbart indlysende; erstat med aktuelt bedste viden, belæg, erfaring, dokumentation eller kvalificeret skøn afhængigt af konteksten",
    1,
    1,
    1,
  ],
  ["check", "checke?", "Stavefejl", "check -> tjek", 1, 1, 1],
  ["kilo", "kilo", "Stavefejl", "kilo -> kg, kilogram", 1, 1, 1],
  ["bekræftige", "bekræftige", "Stavefejl", "bekræftige -> bekræfte", 1, 1, 1],
  [
    "til fulde og fem",
    "til fulde og fem",
    "Generelt",
    "Jeg stoler på ham til fulde/ Jeg er ved mine fulde fem",
    1,
    1,
    1,
  ],
  ["danere", "danere", "Stavefejl", "danere -> daner", 1, 1, 1],
  ["...", "\\S\\.\\.", "Grammatik", "Der skal være mellemrum på begge sider af udeladelsesprikkerne", null, null, null],
  ["catamaran", "catamaran", "Stavefejl", "catamaran -> katamaran", 1, 1, 1],
  ["faldgruppe", "faldgruppe", "Stavefejl", "faldgruppe -> faldgrube", 1, 1, 1],
  ["sovjettiske", "sovjettiske", "Stavefejl", "sovjettiske -> sovjetiske", 1, 1, 1],
  ["som fod i handske", "som fod i handske", "Generelt", "Hånd i handske/ Fod i hose", 1, 1, 1],
  ["filosofen", "filosofen", "Stavefejl", "filosofen -> filosoffen", 1, 1, 1],
  ["risikøer", "risikøer", "Stavefejl", "risikøer -> risikoer eller risici", 1, 1, 1],
  ["næsten", "næsten(?! for godt)", "Fyldeord", "Overvej, om du kan slette eller omformulere", 1, 1, 1],
  ["gjordt", "gjordt", "Generelt", "Den, der staver d i gjort, skal have enden smurt 🤷‍♂️", 1, 1, 1],
  ["lidt", "lidt(?! over)", "Fyldeord", "Overvej, om du kan slette eller omformulere", 1, 1, 1],
  ["nytårsfortsæt", "nytårsfortsæt", "Stavefejl", "nytårsfortsæt -> nytårsforsæt", 1, 1, 1],
  ["friluftsmuseum", "friluftsmuseum", "Stavefejl", "friluftsmuseum -> frilandsmuseum", 1, 1, 1],
  ["landsgreve", "landsgreve", "Stavefejl", "landsgreve -> landgreve", 1, 1, 1],
  ["linie", "linie", "Stavefejl", "linie -> linje", 1, 1, 1],
  ["født bag en vogn", "født bag en vogn", "Generelt", "Jeg er ikke født i går/ Han er ikke tabt bag en vogn", 1, 1, 1],
  ["at ende det", "at ende det", "Generelt", "at afslutte det", 1, 1, 1],
  ["sendebudene", "sendebudene", "Stavefejl", "sendebudene -> sendebuddene", 1, 1, 1],
  ["afsted", "afsted", "Stavefejl", "afsted -> af sted", 1, 1, 1],
  ["anerledes", "anerledes", "Stavefejl", "anerledes -> anderledes", 1, 1, 1],
  ["den søde drik", "den søde drik", "Kliche", "Erstat med original vending", 1, 1, 1],
  [
    "Det tager prisen",
    "((tag(e|er|et)?)|tog) prisen",
    "Anglicisme",
    "Fra det engelske udtryk 'x took the prize as'",
    1,
    1,
    1,
  ],
  ["stramtantet", "stramtantet", "Generelt", "stramtandet", 1, 1, 1],
  ["loden", "loden", "Stavefejl", "loden -> lodden", 1, 1, 1],
  ["Oven i købet", "Oven i købet", "Stavefejl", "ovenikøbet", 1, 1, 1],
  ["arketypisk", "arketypisk", "Generelt", "Mener du 'typisk'?", 1, 1, 1],
  ["ret", "ret(?! til| når)", "Fyldeord", "Overvej, om du kan slette eller omformulere", 1, 1, 1],
  ["incl.", "incl\\.", "Stavefejl", "incl. -> inkl.", 1, 1, 1],
  ["og men", "og men", "Fyldeord", "To konjunktioner her; slet en af dem", 1, 1, 1],
  ["bagklogskabens lys", "bagklogskabens (klare )?lys", "Kliche", "Erstat med original vending", 1, 1, 1],
  ["konstantering", "konstantering", "Stavefejl", "konstantering -> konstatering", 1, 1, 1],
  ["korint", "korint", "Stavefejl", "korint -> korinth", 1, 1, 1],
  ["på mange måder", "på mange måder", "Fyldeord", "Overvej, om du kan slette eller omformulere", 1, 1, 1],
  ["Skagerak", "Skagerak", "Stavefejl", "Skagerak -> Skagerrak", 1, 1, 1],
  ["periferisk", "periferisk", "Stavefejl", "periferisk -> perifer, perifert", 1, 1, 1],
  ["knapt", "knapt", "Stavefejl", "knapt -> knap (dårligt nok; næsten ikke", 1, 1, 1],
  [
    "Fundet mine fødder",
    "(fundet|finder?|fandt) ((m|s|d)ine) fødder",
    "Anglicisme",
    "Fra det engelske udtryk 'to find your footing'",
    1,
    1,
    1,
  ],
  ["jvf.", "jvf\\.", "Stavefejl", "jvf. -> jf.", 1, 1, 1],
  ["kompetance", "kompetance", "Stavefejl", "kompetance -> kompetence", 1, 1, 1],
  ["bogstaveligt talt", "bogstaveligt? talt", "Fyldeord", "Overvej, om du kan slette eller omformulere", 1, 1, 1],
  ["æstimering", "æstimering", "Stavefejl", "æstimering -> estimering", 1, 1, 1],
  ["Hård på", "(har |havde |haft )?hård på", "Anglicisme", "Fra det engelske udtryk 'hard on'", 1, 1, 1],
  ["spydet", "spydet", "Stavefejl", "spydet -> spyddet", 1, 1, 1],
  ["skarpeste kniv i skuffen", "skarpeste kniv i skuffen", "Kliche", "Erstat med original vending", 1, 1, 1],
  ["iår", "iår", "Stavefejl", "iår -> i år", 1, 1, 1],
  ["enormt", "enormt?", "Fyldeord", "Overvej, om du kan slette eller omformulere", 1, 1, 1],
  [
    "alignment",
    "alignment",
    "Anglicisme",
    "Et buzzword, et låneord og en lidt for formel vending går ind på en bar ...",
    1,
    1,
    1,
  ],
  ["excl", "excl", "Stavefejl", "excl -> ekskl.", 1, 1, 1],
  ["dreje nøglen om", "dreje(de|r|t)? nøglen om", "Kliche", "Erstat med original vending", 1, 1, 1],
  [
    "enken til afdød",
    "enken? til afdød|(en afdød)",
    "Dobbeltkonfekt",
    "Det ligger i definitionen af en enke, at det er til en afdød",
    1,
    1,
    1,
  ],
  ["Neksø", "Neksø", "Stavefejl", "Neksø -> Nexø", 1, 1, 1],
  ["ihvertfald", "ihvertfald", "Stavefejl", "ihvertfald -> i hvert fald", 1, 1, 1],
  ["vitterligt", "vitterligt?", "Fyldeord", "Overvej, om du kan slette eller omformulere", 1, 1, 1],
  ["vist", "vist", "Fyldeord", null, 1, 1, 1],
  ["Melanchton", "Melanchton", "Stavefejl", "Melanchton -> Melanchthon", 1, 1, 1],
  ["omstændig", "omstændig", "Stavefejl", "omstændig -> omstændelig", 1, 1, 1],
  [
    "helt til hundene",
    "helt til hundene",
    "Generelt",
    "Sammenblanding af ordsprog (Han er helt til rotterne/ Han er gået i hundene)",
    1,
    1,
    1,
  ],
  ["ethiopier", "ethiopier(e|en)?", "Stavefejl", "ethiopier -> etiopier", 1, 1, 1],
  ["du er velkommen", "du er velkommen", "Kliche", "Erstat med original vending", 1, 1, 1],
  ["altså", "altså", "Fyldeord", "Overvej, om du kan slette eller omformulere", 1, 1, 1],
  ["sæsonnen", "sæsonnen", "Stavefejl", "sæsonnen -> sæsonen", 1, 1, 1],
  ["spydenes", "spydenes", "Stavefejl", "spydenes -> spyddenes", 1, 1, 1],
  ["Gæt hvad", "Gæt hvad\\?", "Anglicisme", "Fra det engelske udtryk 'guess what'", 1, 1, 1],
  ["sprede videre", "spred(e|te|er)? videre", "Dobbeltkonfekt", "Slet 'videre'", 1, 1, 1],
  ["fredsløs", "fredsløse?", "Stavefejl", "fredsløs -> fredløs", 1, 1, 1],
  ["sanskrift", "sanskrift", "Stavefejl", "sanskrift -> sanskrit", 1, 1, 1],
  ["disciplin", "disciplin", "Stavefejl", "disciplin -> disciplin", 1, 1, 1],
  ["ærkebiskopsædet", "ærkebiskopsædet", "Stavefejl", "ærkebiskopsædet -> ærkebispesædet", 1, 1, 1],
  ["melder ud", "meld(t|er|te)? ud", "Dobbeltkonfekt", "Slet 'ud'", 1, 1, 1],
  ["enes med hinanden", "enes med hinanden", "Dobbeltkonfekt", "Slet 'med hinanden'", 1, 1, 1],
  ["pengvinen", "pengvinen", "Stavefejl", "pengvinen -> pingvinen", 1, 1, 1],
  ["resilient", "(resilient|resiliens)", "Buzzword", "Buzzword", 1, 1, 1],
  [
    "hyle mig af pinden",
    "hyle .*af pinden",
    "Generelt",
    "Det kan ikke hyle mig ud af den/ Det kan ikke vippe mig af pinden",
    1,
    1,
    1,
  ],
  ["Bourgoisi", "Bourgoisi", "Stavefejl", "Bourgoisi -> Bourgeoisi", 1, 1, 1],
  ["linkse", "linkse", "Stavefejl", "linkse -> linke", 1, 1, 1],
  ["reelt", "reelt?", "Fyldeord", "Overvej, om du kan slette eller omformulere", 1, 1, 1],
  ["onitologer", "onitologer", "Stavefejl", "onitologer -> ornitologer", 1, 1, 1],
  [
    "Stoppe med",
    "stop(pe|per|pet|pede)? med",
    "Anglicisme",
    "I stedet for at 'stoppe med', så er det bedre dansk at 'holde op med'",
    1,
    1,
    1,
  ],
  ["imorgen", "imorgen", "Stavefejl", "imorgen -> i morgen", 1, 1, 1],
  ["thermisk", "thermisk", "Stavefejl", "thermisk -> termisk", 1, 1, 1],
  ["personificeret", "personificeret", "Generelt", "Mener du personaliseret?", 1, 1, 1],
  ["lys for enden af tunnelen", "lys for enden af tunnelen", "Kliche", "Erstat med original vending", 1, 1, 1],
  ["klokkeslet", "klokkeslet", "Stavefejl", "klokkeslet -> klokkeslæt", 1, 1, 1],
  ["have kant", "ha(r|ft|vde|ve) kant", "Kliche", "Erstat med original vending", 1, 1, 1],
  [
    "udenfor",
    "udenfor(?!\\.)",
    "Grammatik",
    "Erstat med 'uden for'; Via DSN: I over 200 år har der været regler for om man skulle skrive den slags forbindelser i ét eller to ord. Reglerne har dog aldrig ligget fuldstændig fast. Oftest har hovedreglen været sådan at hvis de pågældende ord fungerede som præpositioner (hvis de altså havde en styrelse), skulle de skrives i to ord: den står inden for døren. Hvis de pågældende ord fungerede som adverbialer (hvis de ikke havde en styrelse), skulle de skrives i ét ord: den står indenfor.",
    0,
    1,
    1,
  ],
  ["jorskælv", "jorskælv", "Stavefejl", "jorskælv -> jordskælv", 1, 1, 1],
  ["kirugiske", "kirugiske", "Stavefejl", "kirugiske -> kirurgiske", 1, 1, 1],
  [
    "alt du behøver",
    "alt (du|man|han|hun|den|det|de) (behøver|behøvede)",
    "Generelt",
    "Udvid, så det fx ville hedde 'alt, hvad du behøver'",
    1,
    1,
    1,
  ],
  ["Florens", "Florens", "Stavefejl", "Florens -> Firenze, Florens", 1, 1, 1],
  ["bogtriologi", "bogtriologi", "Stavefejl", "bogtriologi -> bogtrilogi", 1, 1, 1],
  ["tidskronologisk", "tidskronologisk", "Dobbeltkonfekt", "Ordet 'tid' er indbygget i 'kronologisk'", 1, 1, 1],
  ["diskution", "diskution", "Stavefejl", "diskution -> diskussion", 1, 1, 1],
  ["max.", "max\\.", "Stavefejl", "max. -> maks.", 1, 1, 1],
  ["molekylarvægten", "molekylarvægten", "Stavefejl", "molekylarvægten -> molekylvægten", 1, 1, 1],
  ["gulsmed", "gulsmed(e|en)?", "Stavefejl", "gulsmed -> guldsmed", 1, 1, 1],
  ["bærene", "bærene", "Stavefejl", "bærene -> bærrene", 1, 1, 1],
  ["Guiness", "Guiness", "Stavefejl", "Guiness -> Guinness", 1, 1, 1],
  ["øjehøjde", "øjehøjde", "Stavefejl", "øjehøjde -> øjenhøjde", 1, 1, 1],
  ["ursurperet", "ursurperet", "Stavefejl", "ursurperet -> usurperet", 1, 1, 1],
  ["ulinieret", "ulinieret", "Stavefejl", "ulinieret -> ulinjeret", 1, 1, 1],
  ["rammer og tøjler", "rammer og tøjler", "Generelt", "remmer og tøj", 1, 1, 1],
  ["gjorde anledning", "gjorde .*anledning", "Generelt", null, 1, 1, 1],
  ["paradigmaet", "paradigmaet", "Stavefejl", "paradigmaet -> paradigmet", 1, 1, 1],
  ["interessentselskab", "interessentselskab", "Stavefejl", "interessentselskab -> interessentskab", 1, 1, 1],
  ["parafin", "parafin", "Stavefejl", "parafin -> paraffin", 1, 1, 1],
  ["selvfølgelig", "selvfølgelig", "Fyldeord", "Overvej, om du kan slette eller omformulere", 1, 1, 1],
  ["hertig", "hertig", "Stavefejl", "hertig -> hertug", 1, 1, 1],
  ["fornæmme", "fornæmmer?", "Stavefejl", "fornæmme -> fornemme", 1, 1, 1],
  ["udspecificere", "udspecificere(t|de|r)?", "Dobbeltkonfekt", "Slet 'ud'", 1, 1, 1],
  ["på sin vis", "på sin vis", "Fyldeord", "Overvej, om du kan slette eller omformulere", 1, 1, 1],
  ["ganske", "ganske", "Fyldeord", "Overvej, om du kan slette eller omformulere", 1, 1, 1],
  ["Råbe jagt i gevær", "Råbe jagt i gevær", "Generelt", "vagt i gevær", 1, 1, 1],
  ["diamentral", "diamentral(e|t)?", "Stavefejl", "diamentral -> diametral", 1, 1, 1],
  ["diciplin", "diciplin(er)?", "Stavefejl", "diciplin -> disciplin", 1, 1, 1],
  [
    "Vinde ham over",
    "vinde (ham|dem|hende|os) over",
    "Anglicisme",
    "Fra det engelske udtryk 'to win [someone] over'",
    1,
    1,
    1,
  ],
  ["hovede", "hovede", "Stavefejl", "hovede -> hoved", 1, 1, 1],
  ["apperat", "apperat(et|er)?", "Stavefejl", "apperat -> apparat", 1, 1, 1],
  ["statusen", "statusen", "Stavefejl", "statusen -> statussen", 1, 1, 1],
  ["financiere", "financiere(de|r|t)?", "Stavefejl", "financiere -> finansiere", 1, 1, 1],
  ["lesbiske kvinder", "lesbiske? kvinder?", "Dobbeltkonfekt", "Lesbiske er per definition kvinder", 1, 1, 1],
  ["grovfil", "grovfil", "Kliche", "Erstat med original vending", 1, 1, 1],
  ["udrulning", "udrulning", "Kliche", "Erstat med original vending", 1, 1, 1],
  ["feminine kvindelighed", "(feminin|feminine) kvindelighed", "Dobbeltkonfekt", "Slet 'feminin'", 1, 1, 1],
  ["liniær", "liniær", "Stavefejl", "liniær -> lineær", 1, 1, 1],
  ["ursurperede", "ursurperede", "Stavefejl", "ursurperede -> usurperede", 1, 1, 1],
  ["termometmager", "termometmager", "Stavefejl", "termometmager -> termometermager", 1, 1, 1],
  [", vel?", ", vel\\?", "Fyldeord", "Overvej, om du kan slette eller omformulere", 1, 1, 1],
  ["priviligeret", "priviligeret", "Stavefejl", "priviligeret -> privilegeret", 1, 1, 1],
  ["spørge ind til", "((spørg(e|er))|spurgt) ind til", "Dobbeltkonfekt", "spørge til", 1, 1, 1],
  ["bred vifte", "bred vifte", "Kliche", "Erstat med original vending", 1, 1, 1],
  ["export", "export", "Stavefejl", "export -> eksport", 1, 1, 1],
  ["gurilla", "gurilla", "Stavefejl", "gurilla -> gorilla, guerilla", 1, 1, 1],
  ["katedral", "katedral", "Stavefejl", "katedral -> domkirke (hovedkirken i et stift)", 1, 1, 1],
  ["gerne", "gerne", "Fyldeord", "Overvej, om du kan slette eller omformulere", 1, 1, 1],
  ["antecipere", "antecipere(r|t|de)?", "Stavefejl", "antecipere -> anticipere", 1, 1, 1],
  ["bolde i luften", "bolde i luften", "Kliche", "Erstat med original vending", 1, 1, 1],
  ["igang", "igang", "Stavefejl", "igang -> i gang", 1, 1, 1],
  ["også", "også(?! i)", "Fyldeord", "Overvej, om du kan slette eller omformulere", 1, 1, 1],
  ["landsgreven", "landsgreven", "Stavefejl", "landsgreven -> landgreven", 1, 1, 1],
  ["gratis gave", "gratis gaver?", "Dobbeltkonfekt", "Gaver er per definition gratis", 1, 1, 1],
  ["et eller andet sted", "et eller andet sted", "Fyldeord", "Overvej, om du kan slette eller omformulere", 1, 1, 1],
  [
    ".....",
    "\\.\\.\\.\\.+",
    "Grammatik",
    "Det skal enten være udeladelsesprikker (3 punktummer med mellemrum på begge sider) eller blot et enkelt punktum",
    1,
    1,
    1,
  ],
  [
    "..",
    "\\.\\.",
    "Grammatik",
    "Det skal enten være udeladelsesprikker (3 punktummer med mellemrum på begge sider) eller blot et enkelt punktum",
    1,
    1,
    1,
  ],
  [
    "skud fra distancen",
    "(skyde|skød|skyder|skudt?) fra distancen",
    "Kliche",
    "Fodboldmetaforer er de værste af alle klichéer",
    1,
    1,
    1,
  ],
  ["nogle gange", "nogle gange", "Fyldeord", "Overvej, om du kan slette eller omformulere", 1, 1, 1],
  ["forlængst", "forlængst", "Stavefejl", "forlængst -> for længst", 1, 1, 1],
  ["idag", "idag", "Stavefejl", "idag -> i dag", 1, 1, 1],
  ["Mange udråbstegn (!!+)", "\\!\\!+", "Grammatik", "Hvad sker der lige her?", 1, 1, 1],
  ["canser", "canser", "Stavefejl", "canser -> cancer, kræft", 1, 1, 1],
  ["lut og lagkage", "lut og lagkage", "Generelt", "lutter lagkage", 1, 1, 1],
  ["liniering", "liniering", "Stavefejl", "liniering -> linjering", 1, 1, 1],
  ["for så vidt angår", "for så vidt angår", "Formelt", "Lidt for formelt", 1, 1, 1],
  ["typper", "typper", "Stavefejl", "typper -> typer", 1, 1, 1],
  ["vigtigeste", "vigtigeste", "Stavefejl", "vigtigeste -> vigtigste", 1, 1, 1],
  ["adlen", "adlen", "Stavefejl", "adlen -> adelen", 1, 1, 1],
  ["overbevidste", "overbevidste", "Stavefejl", "overbevidste -> overbeviste", 1, 1, 1],
  ["iøvrigt", "iøvrigt", "Stavefejl", "iøvrigt -> i øvrigt", 1, 1, 1],
  ["sådan set", "sådan set", "Fyldeord", "Overvej, om du kan slette eller omformulere", 1, 1, 1],
  ["i min optik", "i min optik", "Kliche", "Erstat med original vending", 1, 1, 1],
  ["laubærblade", "laubærblade", "Stavefejl", "laubærblade -> laurbærblade", 1, 1, 1],
  [
    "sættes i båd med ham",
    "sættes i båd med",
    "Generelt",
    "Jeg vil ikke sættes i bås med ham/ Jeg er i samme båd som ham",
    1,
    1,
    1,
  ],
  ["positiv fordel", "positive? fordele?", "Dobbeltkonfekt", "Fordel", 1, 1, 1],
  ["mane fanden på væggen", "(mane|manede|maner|manet) fanden på", "Generelt", "Man 'maler' fanden på væggen", 1, 1, 1],
  ["pencillin", "pencillin", "Stavefejl", "pencillin -> penicillin", 1, 1, 1],
  [
    "være på en rejse",
    "være på en rejse",
    "Kliche",
    "Hvis du rent bogstaveligt talt har været på en rejse, så se bort fra denne",
    1,
    1,
    1,
  ],
  ["temmelig", "temmelig", "Fyldeord", "Overvej, om du kan slette eller omformulere", 1, 1, 1],
  ["premiereministre", "premiereministre", "Stavefejl", "premiereministre -> premierministre", 1, 1, 1],
  ["seperabel", "seperabel", "Stavefejl", "seperabel -> separabel", 1, 1, 1],
  ["bonusen", "bonusens?", "Stavefejl", "bonusen -> bonussen", 1, 1, 1],
  ["tredje gang er lykkens gang", "tredje gang er lykkens gang", "Kliche", "Erstat med original vending", 1, 1, 1],
  ["friluftsmuseer", "friluftsmuseer", "Stavefejl", "friluftsmuseer -> frilandsmuseer", 1, 1, 1],
  ["læreranstalter", "læreranstalter", "Stavefejl", "læreranstalter -> læreanstalter", 1, 1, 1],
  ["vurdere på", "vurdere(r|de|er)? på", "Dobbeltkonfekt", "Slet 'på'", 1, 1, 1],
  ["tænkt for sig selv", "tænk(te|er|t) .*for sig selv", "Dobbeltkonfekt", null, 1, 1, 1],
  ["manet sig op", "(manede|maner|manet) sig", "Generelt", "Man 'mander' sig op", 1, 1, 1],
  [
    "banket ind med skeer",
    "banket ind med skeer",
    "Generelt",
    "De fik det banket ind i hovedet/ De fik det ind med skeer",
    1,
    1,
    1,
  ],
  ["Ikke min ting", "ikke (m|d|s)in ting", "Anglicisme", "Fra det engelske udtryk 'not my thing'", 1, 1, 1],
  ["problemstilling", "problemstilling", "Generelt", "Mener du 'problem'?", 1, 1, 1],
  ["vejne", "vejne", "Stavefejl", "vejne -> vegne", 1, 1, 1],
  ["pulveriserende erhvervsliv", "pulveriserende erhvervsliv", "Kliche", "Erstat med original vending", 1, 1, 1],
  ["fremadrettet", "fremadrettet", "Generelt", "Fremover", 1, 1, 1],
  ["ærgelig", "ærgelig", "Stavefejl", "ærgelig -> ærgerlig", 1, 1, 1],
  ["kollega fra arbejde", "kollega fra .*arbejde", "Dobbeltkonfekt", "Kollega", 1, 1, 1],
  ["Groet op i", "groet op i", "Anglicisme", "Fra det engelske 'grew up in'", 1, 1, 1],
  ["taxonomi", "taxonomi", "Stavefejl", "taxonomi -> taksonomi", 1, 1, 1],
  ["it-teknologi", "(it-teknologi)|(it teknologi)", "Dobbeltkonfekt", "IT", 1, 1, 1],
  ["tilbage igen", "tilbage igen", "Dobbeltkonfekt", null, 1, 1, 1],
  ["desværre", "desværre", "Fyldeord", "Overvej, om du kan slette eller omformulere", 1, 1, 1],
  ["korinterbrev", "korinterbrev", "Stavefejl", "korinterbrev -> korintherbrev", 1, 1, 1],
  ["kom ind i kampen", "kom(me)? ind i kamp(en)?", "Kliche", "Erstat med original vending", 1, 1, 1],
  ["blæreudslet", "blæreudslet", "Stavefejl", "blæreudslet -> blæreudslæt", 1, 1, 1],
  [
    "historik",
    "historik",
    "Typisk anvendt forkert",
    "Betyder ikke historie, men læren om den historiske videnskab",
    1,
    1,
    1,
  ],
  ["accelleration", "accelleration", "Stavefejl", "accelleration -> acceleration", 1, 1, 1],
  ["dødt lig", "dødt lig", "Dobbeltkonfekt", "Det er underforstået, at liget er dødt", 1, 1, 1],
  ["brunede gulve", "brunede gulve", "Generelt", "bonede gulve", 1, 1, 1],
  ["temmeligt", "temmeligt", "Stavefejl", "temmeligt -> temmelig", 1, 1, 1],
  ["interplanetar", "interplanetar", "Stavefejl", "interplanetar -> interplanetarisk", 1, 1, 1],
  ["rimeligt", "rimeligt?", "Fyldeord", "Overvej, om du kan slette eller omformulere", 1, 1, 1],
  ["teleskoper", "teleskoper", "Stavefejl", "teleskoper -> teleskoper, kikkerter", 1, 1, 1],
  ["Bourgoisiet", "Bourgoisiet", "Stavefejl", "Bourgoisiet -> Bourgeoisiet", 1, 1, 1],
  ["toge", "toge", "Stavefejl", "toge -> tog", 1, 1, 1],
  ["strukturede", "strukturede", "Stavefejl", "strukturede -> strukturerede", 1, 1, 1],
  ["max gas", "max gas", "Kliche", "Erstat med original vending", 1, 1, 1],
  ["Rollemodel", "rollemodel", "Anglicisme", "Forbillede", 1, 1, 1],
  ["af staben", "af staben", "Generelt", "af stablen", 1, 1, 1],
  ["tredie", "tredie", "Stavefejl", "tredie -> tredje", 1, 1, 1],
  ["artikelen", "artikelen", "Stavefejl", "artikelen -> artiklen", 1, 1, 1],
  ["Ethiopien", "Ethiopien", "Stavefejl", "Ethiopien -> Etiopien", 1, 1, 1],
  ["bakke baglæns", "bakke(r|t|de)? baglæns", "Dobbeltkonfekt", "Bakke", 1, 1, 1],
  ["forpligte på", "forpligte(r|t|de)? På", "Dobbeltkonfekt", "Slet 'på'", 1, 1, 1],
  ["fælleskab", "fælleskab", "Stavefejl", "fælleskab -> fællesskab", 1, 1, 1],
  ["bare", "bare", "Fyldeord", "Overvej, om du kan slette eller omformulere", 1, 1, 1],
  ["muhammedanske", "muhammedanske", "Stavefejl", "muhammedanske -> muslimske", 1, 1, 1],
  ["extrem", "extrem(e|t)?", "Stavefejl", "extrem -> ekstrem", 1, 1, 1],
  ["bolche", "bolche(r|erne|ernes|rs|s|ts|e)?", "Stavefejl", "bolche -> bolsje", 1, 1, 1],
  ["indcheckning", "indcheckning", "Stavefejl", "indcheckning -> indtjekning", 1, 1, 1],
  ["at brænde for noget", "brænd(e|te|er|t) for", "Kliche", "Erstat med original vending", 1, 1, 1],
  [
    ". Og",
    "\\. Og",
    "Fyldeord",
    'Det kan være OK at starte en sætning med "og", men det er et område, du i det mindste bør overveje at omformulere.',
    0,
    1,
    1,
  ],
  ["snedækt", "snedækt", "Stavefejl", "snedækt -> snedækket", 1, 1, 1],
  ["sportig", "sportig", "Stavefejl", "sportig -> sporty", 1, 1, 1],
  ["tage debatten", "(tage(r|t)?|tog) debatten", "Kliche", "Erstat med original vending", 1, 1, 1],
  ["schuft", "schuft", "Stavefejl", "schuft -> sjuft", 1, 1, 1],
  ["alle gode gange tre", "alle gode gange tre", "Kliche", "Erstat med original vending", 1, 1, 1],
  ["sportigt", "sportigt", "Stavefejl", "sportigt -> sporty", 1, 1, 1],
  ["box", "box", "Stavefejl", "box -> boks", 1, 1, 1],
  ["jagtterminoligi", "jagtterminoligi", "Stavefejl", "jagtterminoligi -> jagtterminologi", 1, 1, 1],
  ["umiddelbart", "umiddelbart", "Fyldeord", null, 1, 1, 1],
  ["embalere", "embalere", "Stavefejl", "embalere -> emballere", 1, 1, 1],
  ["abonere", "abonere(r|de|t)?", "Stavefejl", "abonere -> abonnere", 1, 1, 1],
  ["hjertekuglen", "hjertekuglen", "Generelt", "hjertekulen", 1, 1, 1],
  ["prefix", "prefix", "Stavefejl", "prefix -> præfiks", 1, 1, 1],
  ["interplanetart", "interplanetart", "Stavefejl", "interplanetart -> interplanetarisk", 1, 1, 1],
  ["handle på", "handle(t|r|de)? på", "Dobbeltkonfekt", "Slet 'på'", 1, 1, 1],
  ["ildsprudlende", "ildsprudlende", "Stavefejl", "ildsprudlende -> ildsprudende", 1, 1, 1],
  ["såfremt", "såfremt", "Formelt", "Gammeldags og unødvendigt formelt; erstat med 'hvis'", 1, 1, 1],
  [
    "jeg tænker at",
    "jeg tænker at",
    "Anglicisme",
    "Fra det engelske 'I think that'; erstat med 'jeg tænker mig at'",
    1,
    1,
    1,
  ],
  ["appelere", "appelere(r|t|de)?", "Stavefejl", "appelere -> appellere", 1, 1, 1],
  ["fugleredder", "fugleredder", "Stavefejl", "fugleredder -> fuglereder", 1, 1, 1],
  [
    "bølgerne (havde|har) gået højt",
    "bølgerne (havde|har) gået højt",
    "Kliche",
    "Erstat med original vending",
    1,
    1,
    1,
  ],
  [
    "basilikumspesto",
    "basilikums?pesto",
    "Dobbeltkonfekt",
    "Det er underforstået, at pesto er lavet af basilikum",
    1,
    1,
    1,
  ],
  ["hångklæde", "hångklæde", "Stavefejl", "håndklæde", 1, 1, 1],
  ["geschæft", "geschæft", "Stavefejl", "geschæft -> gesjæft", 1, 1, 1],
  ["holdte", "holdte", "Stavefejl", "holdte -> holdt", 1, 1, 1],
  [
    "Set det komme",
    "(set|så|se) (det)? (ikke)? komme",
    "Anglicisme",
    "Fra det engelske udtryk 'see it coming',",
    1,
    1,
    1,
  ],
  ["omhandle", "omhandle(r|de|t)?", "Formelt", "omhandle -> dreje sig om", 1, 1, 1],
  ["babyloner", "babyloner", "Stavefejl", "babyloner -> babylonier", 1, 1, 1],
  ["statusens", "statusens", "Stavefejl", "statusens -> statussens", 1, 1, 1],
  ["snedækte", "snedækte", "Stavefejl", "snedækte -> snedækkede", 1, 1, 1],
  [
    "en tand mere i posen",
    "en tand mere i posen",
    "Generelt",
    "At give den en tand mere/ At have mere i posen",
    1,
    1,
    1,
  ],
  ["elektricere", "elektricere", "Stavefejl", "elektricere -> elektrisere, elektrificere", 1, 1, 1],
  ["iaften", "iaften", "Stavefejl", "iaften -> i aften", 1, 1, 1],
  ["bølleuvæsen", "bølleuvæsen", "Dobbeltkonfekt", null, 1, 1, 1],
  ["gjordt", "gjordt", "Stavefejl", "gjordt -> gjort", 1, 1, 1],
  ["Padua", "Padua", "Stavefejl", "Padua -> Padova", 1, 1, 1],
  ["jagterminilogi", "jagterminilogi", "Stavefejl", "jagterminilogi -> jagtterminologi", 1, 1, 1],
  ["på årsbasis", "på årsbasis", "Kliche", "Skriv 'om året' i stedet", 1, 1, 1],
  ["hvad angår", "hvad angår", "Formelt", "Lidt for formelt", 1, 1, 1],
  ["for nærværende", "for nærværende", "Formelt", "Erstat med 'i øjeblikket'", 1, 1, 1],
  ["på sigt", "på sigt", "Fyldeord", "Hånden på hjertet: Betyder dette noget konkret i din sætning?", 1, 1, 1],
  ["henvende sig til", "henvende sig til", "Formelt", "henvende sig til -> kontakte, ringe, skrive, komme", 1, 1, 1],
  [
    "så",
    "så(?! ud| meget| er| man| jeg| du| han| hun| den| det| vi| de| mig| os| dem| ham| hende| var| få| kontakt)",
    "Fyldeord",
    "Overvej, om du kan slette 'så' eller omformulere sætningen",
    0,
    1,
    1,
  ],
  ["sendebudenes", "sendebudenes", "Stavefejl", "sendebudenes -> sendebuddenes", 1, 1, 1],
  ["kromosomantallet", "kromosomantallet", "Stavefejl", "kromosomantallet -> kromosomtallet", 1, 1, 1],
  ["mavefornemmelse i kroppen", "mavefornemmelse i (kroppen|(min krop))", "Dobbeltkonfekt", "Mavefornemmelse", 1, 1, 1],
  ["kollonade", "kollonade", "Stavefejl", "kollonade -> kolonnade", 1, 1, 1],
  ["efterkommerer", "efterkommerer", "Stavefejl", "efterkommerer -> efterkommere", 1, 1, 1],
  [
    "sige B, når man har sagt A",
    "sige b,? når (man|han|hun|de|vi) har sagt a",
    "Kliche",
    "Erstat med original vending",
    1,
    1,
    1,
  ],
  ["give et skud på tasken", "give et skud på tasken", "Generelt", "Et skud fra hoften/ Et slag på tasken", 1, 1, 1],
  ["kanadiske", "kanadiske", "Stavefejl", "kanadiske -> canadiske", 1, 1, 1],
  ["åbne op", "åbne(t|r|de)? op", "Dobbeltkonfekt", "Det hedder bare, at man åbner (Man lukker ikke ned)", 1, 1, 1],
  [
    "For hvad det er værd",
    "for hvad,? (det|den|hun|han|de|I|vi) (er|var) værd",
    "Anglicisme",
    "Fra det engelske udtryk 'for what it is worth'",
    1,
    1,
    1,
  ],
  ["i og for sig", "i og for sig", "Fyldeord", "Overvej, om du kan slette eller omformulere", 1, 1, 1],
  ["akkomodere", "akkomodere(r|t|de)?", "Stavefejl", "akkomodere -> akkommodere", 1, 1, 1],
  ["experiment", "experiment(ere|erede|erer)?", "Stavefejl", "experiment -> eksperiment", 1, 1, 1],
  ["tronfølgerloven", "tronfølgerloven", "Stavefejl", "tronfølgerloven -> tronfølgeloven", 1, 1, 1],
  ["sterin", "sterin", "Stavefejl", "sterin -> stearin", 1, 1, 1],
  ["bolsche", "bolsche(r|erne|ernes|rs|s|ts|e)?", "Stavefejl", "bolsche -> bolsje", 1, 1, 1],
  ["parantes", "parantes", "Stavefejl", "parantes -> parentes", 1, 1, 1],
  ["illyriansk", "illyriansk", "Stavefejl", "illyriansk -> illyrisk", 1, 1, 1],
  ["kvadratkilometre", "kvadratkilometre", "Stavefejl", "kvadratkilometre -> kvadratkilometer", 1, 1, 1],
  ["samarbejde i fællesskab", "samarbejde(r|de|t)? i fællesskab", "Dobbeltkonfekt", "Den giver lidt sig selv", 1, 1, 1],
  ["Bourgoisie", "Bourgoisie", "Stavefejl", "Bourgoisie -> Bourgeoisi", 1, 1, 1],
  ["manieret", "manieret", "Stavefejl", "manieret -> maniereret", 1, 1, 1],
  ["sysselssætte", "sysselssætte", "Stavefejl", "sysselssætte -> sysselsætte", 1, 1, 1],
  ["hensynløs", "hensynløs", "Stavefejl", "hensynløs -> hensynsløs", 1, 1, 1],
  ["postbudet", "postbudet", "Stavefejl", "postbudet -> postbuddet", 1, 1, 1],
  ["elekttronisk", "elekttronisk", "Stavefejl", "elekttronisk -> elektronisk", 1, 1, 1],
  [
    "slå en streg i sandet",
    "(slå|slog|slået) ((en streg)|stregen) i sandet",
    "Kliche",
    "Erstat med original vending",
    1,
    1,
    1,
  ],
  ["liniære", "liniære", "Stavefejl", "liniære -> lineære", 1, 1, 1],
  ["Mange spørgsmålstegn (??+)", "\\?\\?+", "Grammatik", "Hvad sker der lige her?", 1, 1, 1],
  ["spotte", "spotte(r|de|t)?", "Anglicisme", "Fra det engelske 'to spot'; erstat med 'opdage'", 1, 1, 1],
  [
    "ragere landet",
    "(reagere|reagerede|reageret|reagerer) (landet|nationen)",
    "Generelt",
    "Man 'regerer' et land",
    1,
    1,
    1,
  ],
  ["hiv-virus", "((hiv-virus)|(hiv virus))", "Dobbeltkonfekt", "HIV", 1, 1, 1],
  ["udmelding", "udmelding", "Dobbeltkonfekt", "Slet 'ud'", 1, 1, 1],
  ["kristen præst", "(kristen|kristne) præst", "Dobbeltkonfekt", "Det er underforstået, at det er kristent", 1, 1, 1],
  ["kollosal", "kollosal(e|t)?", "Stavefejl", "kollosal -> kolossal", 1, 1, 1],
  ["aflevere tilbage", "aflevere(r|t|de)? tilbage", "Dobbeltkonfekt", "Slet 'tilbage'", 1, 1, 1],
  ["brødbetynget", "brødbetynget", "Generelt", "brødebetynget", 1, 1, 1],
  ["Tilbage i", "tilbage i", "Anglicisme", "Fra det engelske udtryk 'back in …'; erstat med 'dengang i'", 1, 1, 1],
  ["vædske", "vædske", "Stavefejl", "vædske -> væske", 1, 1, 1],
  ["Orknøerne", "Orknøerne", "Stavefejl", "Orknøerne -> Orkneyøerne", 1, 1, 1],
  ["intererseret", "intererseret", "Stavefejl", "intererseret -> interesseret", 1, 1, 1],
  ["Komme ned til", "kom(me|met|mer)? ned til", "Anglicisme", "Fra det engelske udtryk 'it comes down to'", 1, 1, 1],
  [
    "måske",
    "måske(?! var| er| kunne| havde| har| fordi)",
    "Fyldeord",
    "Overvej, om du kan slette eller omformulere",
    1,
    1,
    1,
  ],
  ["af vide", "af vide", "Generelt", "at vide", 1, 1, 1],
  ["spydene", "spydene", "Stavefejl", "spydene -> spyddene", 1, 1, 1],
  ["linien", "linien", "Stavefejl", "linien -> linjen", 1, 1, 1],
  ["sattelit", "sattelit", "Stavefejl", "sattelit -> satellit", 1, 1, 1],
  [
    "jødisk rabbiner",
    "jødiske? (rabbiner|synagoge)",
    "Dobbeltkonfekt",
    "Det er underforstået, at det er jødisk",
    1,
    1,
    1,
  ],
  ["maskuline manddom", "maskuline? (mandighed|manddom)", "Dobbeltkonfekt", "Slet 'maskulin'", 1, 1, 1],
  ["teleskopet", "teleskopet", "Stavefejl", "teleskopet -> teleskopet, kikkerten", 1, 1, 1],
  ["udmelde", "udmeld(e|er|te)?", "Dobbeltkonfekt", "Slet 'ud'", 1, 1, 1],
  ["sendebudet", "sendebudet", "Stavefejl", "sendebudet -> sendebuddet", 1, 1, 1],
  ["virkelig", "virkelig", "Fyldeord", "Overvej, om du kan slette eller omformulere", 1, 1, 1],
  ["Celcius", "Celcius", "Stavefejl", "Celcius -> Celsius", 1, 1, 1],
  [", ikke?", ", ikke\\?", "Fyldeord", "Overvej, om du kan slette eller omformulere", 1, 1, 1],
  [null, null, "Formelt", null, null, null, null],
  ["tourmalin", "tourmalin", "Stavefejl", "tourmalin -> turmalin", 1, 1, 1],
  ["skudt og dræbt", "skudt og dræbt", "Anglicisme", "Fra det engelske 'shot and killed'; erstat med 'skudt'", 1, 1, 1],
  ["Frederikstaden", "Frederikstaden", "Stavefejl", "Frederikstaden -> Frederiksstaden", 1, 1, 1],
  [
    "Sætte det på linen",
    "(sætter?|sat(te)?) (det )?på linj?en",
    "Anglicisme",
    "Fra det engelske udtryk 'put on the line'",
    1,
    1,
    1,
  ],
  ["gode råd har været dyre", "gode råd (har|havde) været dyre", "Kliche", "Erstat med original vending", 1, 1, 1],
  ["hårfrisure", "hårfrisure|hår-frisure", "Dobbeltkonfekt", "Den giver lidt sig selv", 1, 1, 1],
  ["biblotek", "biblotek", "Stavefejl", "biblotek -> bibliotek", 1, 1, 1],
  [
    "forandringsparat",
    "forandringsparat",
    "Buzzword",
    "Buzzword, der typisk ikke fortæller meget; erstat med eksempler på forandringsparatheden",
    1,
    1,
    1,
  ],
  ["bonuser", "bonuser(ne|nes|rs)?", "Stavefejl", "bonuser -> bonusser", 1, 1, 1],
  ["Florentz", "Florentz", "Stavefejl", "Florentz -> Firenze, Florens", 1, 1, 1],
  ["vantrohed", "vantrohed", "Stavefejl", "vantrohed -> vantro", 1, 1, 1],
  ["kilomet", "kilomet\\b", "Stavefejl", "kilomet -> kilometer", 1, 1, 1],
  [
    "jeg mener",
    "jeg mener",
    "Fyldeord",
    "Det er typisk underforstået, at teksten er udtryk for dine holdinger",
    1,
    1,
    1,
  ],
  ["allesammen", "allesammen", "Stavefejl", "allesammen -> alle sammen", 1, 1, 1],
  ["vædsker", "vædsker", "Stavefejl", "vædsker -> væsker", 1, 1, 1],
  ["uværgelig", "uværgelig", "Stavefejl", "uværgelig -> uvægerlig", 1, 1, 1],
  ["svinggerninger", "svinggerninger", "Generelt", "svinkeærinder", 1, 1, 1],
  ["gramatik", "gramatik", "Stavefejl", "gramatik -> grammatik", 1, 1, 1],
  ["prøve kræfter med", "prøve(t|er|de)? kræfter med", "Kliche", "Erstat med original vending", 1, 1, 1],
  ["overvinte", "overvinte", "Stavefejl", "overvinte -> overvintre", 1, 1, 1],
  ["protokoler", "protokoler", "Stavefejl", "protokoler -> protokoller", 1, 1, 1],
  ["budets", "budets", "Stavefejl", "budets -> buddets", 1, 1, 1],
  ["i baghånden", "i baghånden", "Kliche", "Erstat med original vending", 1, 1, 1],
  ["livstruende mordforsøg", "livstruende (mord|attentat)forsøg", "Dobbeltkonfekt", "Mordforsøg", 1, 1, 1],
  [
    "lagt på sofaen",
    "lagt på sofa(en)?",
    "Generelt",
    "Man lægger sig på en sofa og har derefter ligget på den; man har ikke 'lagt' på den",
    1,
    1,
    1,
  ],
  ["øjjet", "øjjet", "Stavefejl", "øjjet -> øjet", 1, 1, 1],
  ["Appeninerne", "Appeninerne", "Stavefejl", "Appeninerne -> Appenninerne", 1, 1, 1],
  ["ynglings", "ynglings.*\\b", "Generelt", "Det er 'yndling', som i 'det er mit yndlingsbillede'", 1, 1, 1],
  ["skudet", "skudet", "Stavefejl", "skudet -> skuddet", 1, 1, 1],
  ["Pommeren", "Pommeren", "Stavefejl", "Pommeren -> Pommern", 1, 1, 1],
  ["vædskens", "vædskens", "Stavefejl", "vædskens -> væskens", 1, 1, 1],
  ["have ja-hatten på", "(har|have|havde|haft) ja-hat(ten)?", "Kliche", "Erstat med original vending", 1, 1, 1],
  ["købmandsskab", "købmandsskab", "Stavefejl", "købmandsskab -> købmandskab", 1, 1, 1],
  [
    "diskurs",
    "diskurs",
    "Typisk anvendt forkert",
    "Erstat evt. med frase, ord debat, sprogbrug eller diskussion",
    1,
    1,
    1,
  ],
  ["tilskuerepladser", "tilskuerepladser", "Stavefejl", "tilskuerepladser -> tilskuerpladser", 1, 1, 1],
  ["overbevidst", "overbevidst", "Stavefejl", "overbevidst -> overbevist", 1, 1, 1],
  ["det mest optimale ville være", "det mest optimale vil(le)? være", "Kliche", "Erstat med original vending", 1, 1, 1],
  ["hududslet", "hududslet", "Stavefejl", "hududslet -> hududslæt, udslæt", 1, 1, 1],
  ["Konstatinopel", "Konstatinopel", "Stavefejl", "Konstatinopel -> Konstantinopel", 1, 1, 1],
  ["eventuelt", "eventuelt?", "Fyldeord", "Overvej, om du kan slette eller omformulere", 1, 1, 1],
  ["i mine øjne", "i mine øjne", "Fyldeord", "Overvej, om du kan slette eller omformulere", 1, 1, 1],
  ["omforandring", "omforandring", "Dobbeltkonfekt", "Det er blot 'forandring'", 1, 1, 1],
  ["På daglig basis", "på daglig basis", "Anglicisme", "Fra det engelske udtryk 'on a daily basis',", 1, 1, 1],
  ["faldgrupper", "faldgrupper", "Generelt", "faldgruber", 1, 1, 1],
  ["grønsværet", "grønsværet", "Stavefejl", "grønsværet -> grønsværen", 1, 1, 1],
  ["luftstyrke", "luftstyrke", "Stavefejl", "luftstyrke -> luftvåben, flyvevåben", 1, 1, 1],
  ["som, der", "som,? der", "Dobbeltkonfekt", "Slet 'der'", 1, 1, 1],
  ["applomb", "applomb", "Stavefejl", "applomb -> aplomb", 1, 1, 1],
  ["tone sig op", "(tone|toner|tonede|tonet) sig op", "Generelt", "Man 'tårner' sig op", 1, 1, 1],
  ["starte op", "starte(r|de|t)? op", "Dobbeltkonfekt", "Slet 'op'", 1, 1, 1],
  ["proffessor", "proffessor", "Stavefejl", "proffessor -> professor", 1, 1, 1],
  ["det røde felt", "det røde felt", "Kliche", "Erstat med original vending", 1, 1, 1],
  [
    "sild i en tønde",
    "sild i en tønde",
    "Kliche",
    "Kan du finde en mere original måde i stedet for at læne dig op ad en kliche?",
    1,
    1,
    1,
  ],
  ["anmasende", "anmasende", "Stavefejl", "anmasende -> anmassende", 1, 1, 1],
  ["gevinstrealisering", "(gevinstrealisering|gevinstrealiserede)", "Buzzword", "Buzzword", 1, 1, 1],
  ["interesant", "interesant", "Stavefejl", "interesant -> interessant", 1, 1, 1],
  ["sammenlignes op mod", "sammenlignes op mod", "Generelt", "sammenlignes med", 1, 1, 1],
  ["bødel", "bødel", "Stavefejl", "bødel -> bøddel", 1, 1, 1],
  ["rarieteterne", "rarieteterne", "Stavefejl", "rarieteterne -> rariteterne", 1, 1, 1],
  ["medlemsskab", "medlemsskab", "Stavefejl", "medlemsskab -> medlemskab", 1, 1, 1],
  ["alt andet lige", "alt andet lige", "Fyldeord", "Overvej, om du kan slette eller omformulere", 1, 1, 1],
  ["omfavnet vidt", "(omfavner|omfavnede|omfavnet) vidt", "Generelt", "Man 'favner' vidt", 1, 1, 1],
  ["museumet", "museumet", "Stavefejl", "museumet -> museet", 1, 1, 1],
  ["kanadisk", "kanadisk", "Stavefejl", "kanadisk -> canadisk", 1, 1, 1],
  ["simpelthent", "simpelthent?", "Fyldeord", "Overvej, om du kan slette eller omformulere", 1, 1, 1],
  ["årsagen skyldes at", "årsagen (skyldt?es),? at", "Dobbeltkonfekt", "Den giver lidt sig selv", 1, 1, 1],
  ["ialt", "ialt", "Stavefejl", "ialt -> i alt", 1, 1, 1],
  ["ingen gang på jord", "ingen gang på jord", "Kliche", "Erstat med original vending", 1, 1, 1],
  ["tillbragte", "tillbragte", "Stavefejl", "tillbragte -> tilbragte", 1, 1, 1],
  [
    "Set det sidste af mig",
    "(set|så) det sidste af (mig|ham|hende|den|det|os|dem)",
    "Anglicisme",
    "Fra det engelske udtryk 'seen the last of him'",
    1,
    1,
    1,
  ],
  ["situationstegn", "situationstegn", "Generelt", "citationstegn", 1, 1, 1],
  ["angående", "angående", "Formelt", "Lidt for formelt", 1, 1, 1],
  [
    "alle tøjler over bord",
    "alle tøjler over bord",
    "Generelt",
    "De kaster alt over bord/ De slipper alle tøjler",
    1,
    1,
    1,
  ],
  ["kiruger", "kiruger", "Stavefejl", "kiruger -> kirurger", 1, 1, 1],
  ["vermut", "vermut", "Stavefejl", "vermut -> vermouth", 1, 1, 1],
  ["fat om roden", "fat om roden", "Kliche", "Erstat med original vending", 1, 1, 1],
  ["silicone", "silicone", "Stavefejl", "silicone -> silikone", 1, 1, 1],
  ["selfie af sig selv", "selfie af (dig|en|mig|sig) selv", "Dobbeltkonfekt", "Selfie", 1, 1, 1],
  ["processe", "processe(de|t)?", "Buzzword", "Buzzword", 1, 1, 1],
  ["fordi at", "fordi,? at", "Anglicisme", "fordi at -> fordi", 1, 1, 1],
  ["pytagoras", "pytagoras", "Stavefejl", "pytagoras -> pythagoras", 1, 1, 1],
  [
    "COVID-19 virus",
    "(covid-?19-virus)|(covid-?19 virus)",
    "Dobbeltkonfekt",
    "COVID-19 (eller, hvis vi skal være rigtigt strenge, SARS-CoV-2)",
    1,
    1,
    1,
  ],
  ["Greenwitch", "Greenwitch", "Stavefejl", "Greenwitch -> Greenwich", 1, 1, 1],
  [
    "I hans ret",
    "i (sin|hans|hendes|deres|din|min|vores|jeres)( egen| gode)? ret",
    "Anglicisme",
    "Fra det engelske udtryk 'in his/her own right'",
    1,
    1,
    1,
  ],
  ["dagens lys", "dagens lys", "Kliche", "Erstat med original vending", 1, 1, 1],
  [
    "slå koldt vand i blodet",
    "((slå(r|et)?)|slog) .*koldt vand i blodet",
    "Kliche",
    "Erstat med original vending",
    1,
    1,
    1,
  ],
  ["statusernes", "statusernes", "Stavefejl", "statusernes -> statussernes", 1, 1, 1],
  ["Vende hoveder", "vende hoveder", "Anglicisme", "Fra det engelske udtryk 'turn heads'", 1, 1, 1],
  ["accellerere", "accellerere(r|t)?", "Stavefejl", "accellerere -> accelerere", 1, 1, 1],
  ["meteologi", "meteologi", "Stavefejl", "meteologi -> meteorologi", 1, 1, 1],
  [
    "Bringe til din opmærksomhed",
    "(bringer?|bragte?) .*til (min|din|hans|hendes|dens|deres|vores) opmærksomhed",
    "Anglicisme",
    "Fra det engelske udtryk 'bring to one's attention'",
    1,
    1,
    1,
  ],
  ["konspitorisk", "konspitorisk", "Stavefejl", "konspitorisk -> konspiratorisk", 1, 1, 1],
  ["ben i næsen", "ben i næsen", "Kliche", null, 1, 1, 1],
  ["adminstration", "adminstration", "Stavefejl", "adminstration -> administration", 1, 1, 1],
  ["drifte", "drifte(r|de|t)?", "Buzzword", "Buzzword", 1, 1, 1],
  ["patrioti", "patrioti", "Stavefejl", "patrioti -> patriotisme", 1, 1, 1],
  ["beuf", "beuf", "Stavefejl", "beuf -> boeuf eller bøf", 1, 1, 1],
  [
    " tager det, som det kommer og går",
    " tager? det,? som det kommer og går",
    "Generelt",
    "Det kommer og går/ Hun tager det, som det kommer",
    1,
    1,
    1,
  ],
  ["betegning", "betegning", "Stavefejl", "betegning -> betegnelse", 1, 1, 1],
  ["satelitter", "satelitter", "Stavefejl", "satelitter -> satellitter", 1, 1, 1],
  ["forkromet overblik", "forkrome(t|de) overblik", "Kliche", "Erstat med original vending", 1, 1, 1],
  ["spidse pennen", "spidse(de|r|t)? pennen", "Kliche", "Erstat med original vending", 1, 1, 1],
  ["strøes", "strøes", "Stavefejl", "strøes -> strøs", 1, 1, 1],
  ["absorbtion", "absorbtion", "Stavefejl", "absorbtion -> absorption", 1, 1, 1],
  ["hav en fortsat god dag", "have? en fortsat god dag", "Kliche", "Erstat med original vending", 1, 1, 1],
  ["skredene", "skredene", "Stavefejl", "skredene -> skreddene", 1, 1, 1],
  ["premiereminister", "premiereminister", "Stavefejl", "premiereminister -> premierminister", 1, 1, 1],
  ["komme ud over rampen", "kom(me)? ud over rampen", "Kliche", null, 1, 1, 1],
  ["tilflugssted", "tilflugssted", "Stavefejl", "tilflugssted -> tilflugtssted", 1, 1, 1],
  [
    "skelne til",
    "(skelne|skelnede|skelnet|skelner) til",
    "Generelt",
    "Mener du 'skele' i stedet for 'skelne'?",
    1,
    1,
    1,
  ],
  ["Skindet bedrager", "Skindet bedrager", "Generelt", "skinnet", 1, 1, 1],
  ["globaliseret verden", "globalisere(t|de) verden", "Kliche", "Erstat med original vending", 1, 1, 1],
  ["territotale", "territotale", "Stavefejl", "territotale -> territoriale", 1, 1, 1],
  ["kappe over", "kappe(de|r|t)? over", "Generelt", "Det hedder 'kamme' over", 1, 1, 1],
  ["hængt flaget", "hængt (Dannebrog|flaget|flag)", "Generelt", "Hejst!", 1, 1, 1],
  ["tøjleløse", "tøjleløse", "Stavefejl", "tøjleløse -> tøjlesløse", 1, 1, 1],
  ["kirug", "kirug", "Stavefejl", "kirug -> kirurg", 1, 1, 1],
  ["planktonnet", "planktonnet", "Stavefejl", "planktonnet -> planktonet", 1, 1, 1],
  ["Scotland", "Scotland", "Stavefejl", "Scotland -> Skotland", 1, 1, 1],
  ["dråben af isbjerget", "dråben af isbjerget", "Generelt", "En dråbe i havet/ Toppen af isbjerget", 1, 1, 1],
  ["trak en mine", "trak .*en mine", "Generelt", null, 1, 1, 1],
  ["nemligt", "nemligt", "Stavefejl", "nemligt -> nemlig", 1, 1, 1],
  [
    "når man har sagt A, så må man også sige B",
    "når man har sagt A,? (så )?må man .* sige B",
    "Kliche",
    "Erstat med original vending",
    1,
    1,
    1,
  ],
  ["Tabt for ord", "tabt for ord", "Anglicisme", "Fra det engelske udtryk 'lost for words',", 1, 1, 1],
  ["sætte i scene", "(sætter?|sat(te)?) i scene", "Kliche", "Erstat med original vending", 1, 1, 1],
  ["endvidere", "endvidere", "Formelt", "endvidere -> derudover, desuden", 1, 1, 1],
  ["liniært", "liniært", "Stavefejl", "liniært -> lineært", 1, 1, 1],
  ["Svejts", "Svejts", "Stavefejl", "Svejts -> Schweiz", 1, 1, 1],
  ["hieraki", "hieraki", "Stavefejl", "hieraki -> hierarki", 1, 1, 1],
  ["gøre en forskel", "(gører?|gjort) en forskel", "Kliche", "Erstat med original vending", 1, 1, 1],
  ["statuser", "statuser", "Stavefejl", "statuser -> statusser", 1, 1, 1],
  ["Papyrussejr", "Papyrussejr", "Generelt", "pyrrhussejr", 1, 1, 1],
  ["hele", "hele (?!mit|min)", "Fyldeord", "Overvej, om du kan slette eller omformulere", 1, 1, 1],
  [
    "jeg synes",
    "jeg synes",
    "Fyldeord",
    "Det er typisk underforstået, at teksten er udtryk for dine holdinger",
    1,
    1,
    1,
  ],
  ["syntax", "syntax", "Stavefejl", "syntax -> syntaks", 1, 1, 1],
  ["forpubbe", "forpubbe", "Stavefejl", "forpubbe -> forpuppe", 1, 1, 1],
  ["agressiv", "agressiv", "Stavefejl", "agressiv -> aggressiv", 1, 1, 1],
  ["stamme tilbage fra", "stamme(r|de|t)? tilbage fra", "Dobbeltkonfekt", "Slet 'tilbage'", 1, 1, 1],
  ["tage roret", "((tage(r|t)?)|tog) roret", "Kliche", "Erstat med original vending", 1, 1, 1],
  ["fagterm", "fagterm", "Stavefejl", "fagterm -> fagudtryk", 1, 1, 1],
  ["gribe knoglen", "(grib(e)?|greb(et)?) knoglen", "Kliche", "Erstat med original vending", 1, 1, 1],
  ["strukket", "strukket", "Stavefejl", "strukket -> strakt", 1, 1, 1],
  ["krum hals", "krum hals", "Kliche", "Erstat med original vending", 1, 1, 1],
  ["lus på gangene", "lus på gangene", "Generelt", "lus på gangen", 1, 1, 1],
  ["ekstremt", "ekstremt?", "Fyldeord", "Overvej, om du kan slette eller omformulere", 1, 1, 1],
  ["skudene", "skudene", "Stavefejl", "skudene -> skuddene", 1, 1, 1],
  ["softiceis", "softice-is|(softice is)|softiceis", "Dobbeltkonfekt", "Softice", 1, 1, 1],
  ["konkludere på", "konkludere(r|t|de)? på", "Dobbeltkonfekt", "Slet 'på'", 1, 1, 1],
  ["fx.", "fx\\.", "Stavefejl", "fx. -> fx", 1, 1, 1],
  ["læreranstalt", "læreranstalt", "Stavefejl", "læreranstalt -> læreanstalt", 1, 1, 1],
  ["Faldet til rette", "(faldet|falder|faldt) til rette", "Generelt", "Fjern 'rette'", 1, 1, 1],
  ["manierede", "manierede", "Stavefejl", "manierede -> maniererede", 1, 1, 1],
  ["incl", "incl", "Stavefejl", "incl -> inkl.", 1, 1, 1],
  ["Johanitterordenen", "Johanitterordenen", "Stavefejl", "Johanitterordenen -> Johanniterordenen", 1, 1, 1],
  ["udflod", "udflod", "Stavefejl", "udflod -> udflåd", 1, 1, 1],
  ["anderkendt", "anderkendt", "Stavefejl", "anderkendt -> anerkendt", 1, 1, 1],
  ["livsline", "livsline", "Stavefejl", "livsline -> livline", 1, 1, 1],
  ["jagterminoligi", "jagterminoligi", "Stavefejl", "jagterminoligi -> jagtterminologi", 1, 1, 1],
  ["Taleban", "Taleban", "Stavefejl", "Taleban -> Taliban", 1, 1, 1],
  ["påbudet", "påbudet", "Stavefejl", "påbudet -> påbuddet", 1, 1, 1],
  [
    "jeg tænker",
    "jeg tænker",
    "Fyldeord",
    "Som Information skriver: Ingen vil bare 'synes, 'føle', eller 'mene' noget. Ved at sige 'jeg tænker' antydes det, at der ligger gennemarbejdet argumentation bag udsagnet, hvad der kun sjældent egentligt er tilfældet.",
    1,
    1,
    1,
  ],
  ["statusers", "statusers", "Stavefejl", "statusers -> statussers", 1, 1, 1],
  ["sendebudets", "sendebudets", "Stavefejl", "sendebudets -> sendebuddets", 1, 1, 1],
  ["matematikerer", "matematikerer", "Stavefejl", "matematikerer -> matematikere", 1, 1, 1],
  ["navnligt", "navnligt", "Stavefejl", "navnligt -> navnlig", 1, 1, 1],
  ["ligemeget", "ligemeget", "Stavefejl", "lige meget", 1, 1, 1],
  ["max", "max", "Stavefejl", "max -> maks.", 1, 1, 1],
  ["postbuddene", "postbuddene", "Stavefejl", "postbuddene -> postbudene", 1, 1, 1],
  ["novelist", "novelist", "Stavefejl", "novelist -> romanforfatter", 1, 1, 1],
  ["begge ben i næsen", "begge ben i næsen", "Generelt", "Hun har ben i næsen/ Hun har begge ben på jorden", 1, 1, 1],
  ["addresse", "addresse(n|r)?", "Stavefejl", "addresse -> adresse", 1, 1, 1],
  ["disrespekt", "disrespekt", "Anglicisme", "Fra det engelske 'disrespect'; erstat med 'despekt'", 1, 1, 1],
  ["Kanada", "Kanada", "Stavefejl", "Kanada -> Canada", 1, 1, 1],
  [
    "holde tænderne lige i munden",
    "holde tænderne lige i munden",
    "Generelt",
    "At holde tungen lige i munden",
    1,
    1,
    1,
  ],
  ["taxonomisk", "taxonomisk", "Stavefejl", "taxonomisk -> taksonomisk", 1, 1, 1],
  ["reflektion", "reflektion", "Stavefejl", "reflektion -> refleksion", 1, 1, 1],
  ["Mosegårdskov", "Mosegårdskov", "Stavefejl", "Mosegårdskov -> Moesgård Skov", 1, 1, 1],
  ["Intention", "intention", "Anglicisme", "Erstattes med det danske ord 'hensigt'", 1, 1, 1],
  ["kirugisk", "kirugisk", "Stavefejl", "kirugisk -> kirurgisk", 1, 1, 1],
  ["centaur", "centaur", "Stavefejl", "centaur -> kentaur", 1, 1, 1],
  ["ift.", "ift\\.?", "Typisk anvendt forkert", "Erstat evt. med 'for' eller 'til'", 1, 1, 1],
  ["bølgerne vil gå højt", "bølgerne vil gå højt", "Kliche", "Erstat med original vending", 1, 1, 1],
  ["teleskop", "teleskop", "Stavefejl", "teleskop -> teleskop, kikkert", 1, 1, 1],
  ["lation", "lation", "Stavefejl", "lation -> latin", 1, 1, 1],
  ["pludselig", "pludseligt?", "Fyldeord", "Overvej, om du kan slette eller omformulere", 1, 1, 1],
  ["mørkglødet", "mørkglødet", "Generelt", "mørklødet", 1, 1, 1],
  ["fremfor", "fremfor", "Stavefejl", "fremfor -> frem for", 1, 1, 1],
  ["direktøre", "direktøre", "Stavefejl", "direktører", 1, 1, 1],
  ["slå på tråden", "(slå(r|et)?|slog) på tråden", "Kliche", "Erstat med original vending", 1, 1, 1],
  ["gotisk knude", "gotiske? knuder?", "Generelt", "gordisk knude", 1, 1, 1],
  ["dongeons", "dongeons", "Stavefejl", "dongeons -> dungeons", 1, 1, 1],
  ["læreranstalten", "læreranstalten", "Stavefejl", "læreranstalten -> læreanstalten", 1, 1, 1],
  ["ærende", "ærende", "Stavefejl", "ærende -> ærinde", 1, 1, 1],
  [
    "skuespilsforfatter",
    "skuespilsforfatter",
    "Stavefejl",
    "skuespilsforfatter -> skuespilforfatter, dramatiker",
    1,
    1,
    1,
  ],
  ["messehaglet", "messehaglet", "Stavefejl", "messehaglet -> messehagelen", 1, 1, 1],
  ["krøller tommelfingre", "krøller tommelfingre", "Generelt", "Krummer tæer/ Triller tommelfingre", 1, 1, 1],
  ["resortområdet?", "resortområdet?", "Dobbeltkonfekt", "Et resort *er* et område", 1, 1, 1],
  ["testforsøg", "testforsøg", "Dobbeltkonfekt", null, 1, 1, 1],
  ["filipinsk", "filipinsk", "Stavefejl", "filipinsk -> filippinsk", 1, 1, 1],
  [
    "muligheder frem for begrænsninger",
    "muligheder frem for begrænsninger",
    "Kliche",
    "Erstat med original vending",
    1,
    1,
    1,
  ],
  ["jagterminologi", "jagterminologi", "Stavefejl", "jagterminologi -> jagtterminologi", 1, 1, 1],
  ["indeholdte", "indeholdte", "Stavefejl", "indeholdte -> indeholdt (hvis verbum", 1, 1, 1],
  ["bleg om ørene", "bleg om ørene", "Generelt", "Han var bleg om næbbet/ Han blev hed om ørene", 1, 1, 1],
  ["thermiske", "thermiske", "Stavefejl", "thermiske -> termiske", 1, 1, 1],
  ["helt", "helt(?! menneske)", "Fyldeord", "Overvej, om du kan slette (hvis ordet er anvendt som adjektiv)", 1, 1, 1],
  ["summere sammen", "summere(r|t|de)? sammen", "Dobbeltkonfekt", "Slet 'sammen'", 1, 1, 1],
  ["Men alligevel", "men alligevel", "Anglicisme", "Fra det engelske udtryk 'but still'", 1, 1, 1],
  ["rund cirkel", "runde? cirkel|cirkler", "Dobbeltkonfekt", "Cirkler er per definition runde", 1, 1, 1],
  ["i min verden", "i min verden", "Kliche", "Erstat med original vending", 1, 1, 1],
  ["udemærket", "udemærket", "Stavefejl", "udemærket -> udmærket", 1, 1, 1],
  [" men", "[^\\,\\.\\:\\;\\>]\\smen", "Grammatik", "Mangler der et komma her?", 0, 1, 1],
  ["istedet for", "istedet for", "Stavefejl", "istedet for -> i stedet for", 1, 1, 1],
  [
    "disruption",
    "disruption",
    "Buzzword",
    "Buzzword, der typisk ikke fortæller meget; erstat med eksempler på, hvordan der 'disruptes'",
    1,
    1,
    1,
  ],
  ["egentlig", "egentlig(t|e)?", "Fyldeord", "Overvej, om du kan slette eller omformulere", 1, 1, 1],
  ["vædskerne", "vædskerne", "Stavefejl", "vædskerne -> væskerne", 1, 1, 1],
  ["distribuere ud", "distribuere(t|de|r)? Ud", "Dobbeltkonfekt", "Slet 'ud'", 1, 1, 1],
  ["bakker op", "bakke(r|t|de)? op", "Dobbeltkonfekt", "Slet 'op'", 1, 1, 1],
  ["problemmer", "problemmer", "Stavefejl", "problemmer -> problemer", 1, 1, 1],
  ["Ment for", "ment for", "Anglicisme", "Fra det engelske udtryk 'meant for'", 1, 1, 1],
  ["Den anden dag", "den anden dag", "Anglicisme", "Fra det engelske udtryk 'the other day'", 1, 1, 1],
  ["igår", "igår", "Stavefejl", "igår -> i går", 1, 1, 1],
  ["kalendre", "kalendre", "Stavefejl", "kalendre -> kalendere", 1, 1, 1],
  ["antageligvis", "antageligvis", "Stavefejl", "antageligvis -> antagelig", 1, 1, 1],
  ["muhammedansk", "muhammedansk", "Stavefejl", "muhammedansk -> muslimsk", 1, 1, 1],
  ["bronce", "bronce", "Stavefejl", "bronce -> bronze", 1, 1, 1],
  ["stadions", "stadions", "Stavefejl", "stadions -> stadioner", 1, 1, 1],
  ["gule og grønne skove", "gule og grønne skove", "Generelt", "guld og grønne skove", 1, 1, 1],
  ["dongeon", "dongeon", "Stavefejl", "dongeon -> dungeon", 1, 1, 1],
  ["psykiatriker", "psykiatriker", "Stavefejl", "psykiatriker -> psykiater", 1, 1, 1],
  ["akkomodation", "akkomodation", "Stavefejl", "akkomodation -> akkommodation", 1, 1, 1],
  ["förmyndarregering", "förmyndarregering", "Stavefejl", "förmyndarregering -> formynderregering", 1, 1, 1],
  ["tackle problemet", "tackle(r|de|t)? (problemet|(et problem))", "Kliche", "Erstat med original vending", 1, 1, 1],
  ["æstime", "æstime", "Stavefejl", "æstime -> estime", 1, 1, 1],
  [
    "Hænge ud med",
    "((hæng(e|er|t)?)|hang) ud med",
    "Anglicisme",
    "Fra det engelske udtryk 'to hang out with'",
    1,
    1,
    1,
  ],
  ["serumsinstitut", "serumsinstitut", "Stavefejl", "serumsinstitut -> seruminstitut", 1, 1, 1],
  [
    "verdenen",
    "verdenen",
    "Stavefejl",
    "verdenen -> verden; dog -verdenen i sammensatte ord som filmverdenen",
    1,
    1,
    1,
  ],
  [
    "der, skoen ligger begravet",
    "der,? skoen ligger begravet",
    "Generelt",
    "Det er der, hunden ligger begravet/ Det er der skoen trykker",
    1,
    1,
    1,
  ],
  ["Give det et skud", "(give?r?|gav) .* et skud", "Anglicisme", "Fra det engelske 'give it a shot'", 1, 1, 1],
  [
    "undertøj for hende",
    "(under)?tøj for (hende|ham)",
    "Anglicisme",
    "Fra det engelske udtryk 'underwear for her' (på dansk: *Til* hende)",
    1,
    1,
    1,
  ],
  ["æstimere", "æstimere", "Stavefejl", "æstimere -> estimere", 1, 1, 1],
  ["svaghed for", "svaghed for(.{0,10})?", "Anglicisme", "Fra det engelske udtryk 'a weakness for [x]'", 1, 1, 1],
  ["gode råd er dyre", "gode råd (er|var) dyre", "Kliche", "Erstat med original vending", 1, 1, 1],
  ["generalogi", "generalogi", "Stavefejl", "generalogi -> genealogi", 1, 1, 1],
  ["sterefoni", "sterefoni", "Stavefejl", "sterefoni -> stereofoni", 1, 1, 1],
  ["dimisioner", "dimisioner", "Stavefejl", "dimisioner -> dimissioner, dimensioner", 1, 1, 1],
  ["tilbudene", "tilbudene", "Stavefejl", "tilbudene -> tilbuddene", 1, 1, 1],
  ["Poland", "Poland", "Stavefejl", "Poland -> Polen", 1, 1, 1],
  ["man kan sige, at", "man kan sige,? at", "Fyldeord", "Overvej, om du kan slette eller omformulere", 1, 1, 1],
  ["cencur", "cencur", "Stavefejl", "cencur -> censur", 1, 1, 1],
  ["parantetisk", "parantetisk", "Stavefejl", "parantetisk -> parentetisk", 1, 1, 1],
  [
    "agil",
    "agil(t|e|itet)?",
    "Buzzword",
    "Buzzword; har en specifik betydning, men mister den lidt, når man bruger den 35x i træk",
    1,
    1,
    1,
  ],
  ["Gro et skæg", "(gro|groede) (et)? skæg(get)?", "Anglicisme", "Fra det engelske udtryk 'grow a beard'", 1, 1, 1],
  ["staniol", "staniol", "Stavefejl", "staniol -> stanniol", 1, 1, 1],
  [
    "ildsjæl",
    "ildsjæl",
    "Kliche",
    "Opvasker søges - er du ildsjæl, og brænder du for rene tallerkener? Lad nu være'",
    1,
    1,
    1,
  ],
  ["progrom", "progrom", "Stavefejl", "progrom -> pogrom, program", 1, 1, 1],
  ["male fanden på væggen", "male(de|t|r)? fanden på væggen", "Kliche", "Erstat med original vending", 1, 1, 1],
  ["kirugien", "kirugien", "Stavefejl", "kirugien -> kirurgien", 1, 1, 1],
  ["reperation", "reperation", "Stavefejl", "reperation -> reparation", 1, 1, 1],
  ["skredenes", "skredenes", "Stavefejl", "skredenes -> skreddenes", 1, 1, 1],
  ["lissom", "lissom", "Fyldeord", "Overvej, om du kan slette eller omformulere", 1, 1, 1],
  ["spydets", "spydets", "Stavefejl", "spydets -> spyddets", 1, 1, 1],
  ["prositueret", "prositueret", "Stavefejl", "prositueret -> prostitueret", 1, 1, 1],
  ["koleratur", "koleratur", "Stavefejl", "koleratur -> koloratur", 1, 1, 1],
  [
    "fingrene fra fedtefadet",
    "fingrene fra fedtefadet",
    "Generelt",
    "De kan ikke holde fingrene af fadet/ De kommer i fedtefadet",
    1,
    1,
    1,
  ],
  ["selvskab", "selvskab", "Stavefejl", "selvskab -> selskab", 1, 1, 1],
  ["dilletant", "dilletant", "Stavefejl", "dilletant -> dilettant", 1, 1, 1],
  ["paradigma", "paradigma", "Stavefejl", "paradigma -> paradigme", 1, 1, 1],
  ["lydeløs", "lydeløs", "Stavefejl", "lydeløs -> lydefri, lydløs", 1, 1, 1],
  ["muslimsk imam", "muslimske? (imam|moske)", "Dobbeltkonfekt", "Det er underforstået, at det er muslimsk", 1, 1, 1],
  ["Garone", "Garone", "Stavefejl", "Garone -> Garonne", 1, 1, 1],
  ["museumets", "museumets", "Stavefejl", "museumets -> museets", 1, 1, 1],
  ["mythologi", "mythologi", "Stavefejl", "mythologi -> mytologi", 1, 1, 1],
  ["linkser", "linkser", "Stavefejl", "linkser -> links (?", 1, 1, 1],
  ["frådse", "frådse", "Stavefejl", "frådse -> fråse", 1, 1, 1],
  [
    "Have din ryg",
    "(har|have|havde|haft|hav) (din|hans|hendes|ens|deres|jeres|vores) ryg",
    "Anglicisme",
    "Fra det engelske udtryk 'I've got your back'",
    1,
    1,
    1,
  ],
  ["borgerdydsskole", "borgerdydsskole", "Stavefejl", "borgerdydsskole -> borgerdydskole", 1, 1, 1],
  ["dilerium", "dilerium", "Stavefejl", "dilerium -> delirium", 1, 1, 1],
  ["ugift ungkarl", "ugifte? ungkarle?", "Dobbeltkonfekt", "Ungkarle er per definition ugifte", 1, 1, 1],
  ["kenetegnet", "kenetegnet", "Stavefejl", "kenetegnet -> kendetegnet", 1, 1, 1],
  ["paradigmaer", "paradigmaer", "Stavefejl", "paradigmaer -> paradigmer", 1, 1, 1],
  ["dog", "dog", "Fyldeord", null, 1, 1, 1],
  ["Schweitz", "Schweitz", "Stavefejl", "Schweitz -> Schweiz", 1, 1, 1],
  ["tvetydeligt", "tvetydeligt", "Generelt", "tvetydigt", 1, 1, 1],
  ["kemikalium", "kemikalium", "Stavefejl", "kemikalium -> kemikalie", 1, 1, 1],
  [
    "blæse og have rent mel i posen",
    "blæse og have rent mel i posen",
    "Generelt",
    "Man kan ikke både blæse og have mel i munden/ At have rent mel i posen",
    1,
    1,
    1,
  ],
  ["alligevel", "alligevel", "Fyldeord", "Overvej, om du kan slette eller omformulere", 1, 1, 1],
  ["farcisk", "(farcisk|farciskt)", "Generelt", "Mener du farceagtigt eller facistisk?", 1, 1, 1],
  ["tilbudet", "tilbudet", "Stavefejl", "tilbudet -> tilbuddet", 1, 1, 1],
  [
    "Det køber jeg ikke ind i",
    "køb(er?|te)? .*ind i (.{0,10})",
    "Anglicisme",
    "Fra det engelske udtryk 'buy into [something]'",
    1,
    1,
    1,
  ],
  ["skyskrabere for øjnene", "skyskrabere for øjnene", "Generelt", "At have skyklapper for øjnene", 1, 1, 1],
  ["foreksempel", "foreksempel", "Stavefejl", "foreksempel -> for eksempel", 1, 1, 1],
  ["værge sig", "værge sig", "Generelt", "værge for sig", 1, 1, 1],
  [
    "Glücksburgske",
    "Glücksburgske",
    "Stavefejl",
    "Glücksburgske -> Glücksborgske (i forbindelse med kongehuset)",
    1,
    1,
    1,
  ],
  ["luderkoldt vand", "luderkoldt vand", "Generelt", "lud og koldt vand", 1, 1, 1],
  ["chock", "chock", "Stavefejl", "chock -> chok", 1, 1, 1],
  ["henved", "henved", "Stavefejl", "henved -> hen ved", 1, 1, 1],
  ["op ad bakke", "op ad bakke", "Kliche", "Erstat med original vending", 1, 1, 1],
  ["stå på mål", "(stå(r|et)?|stod) på mål", "Kliche", "Fodboldmetaforer er de værste af alle klichéer", 1, 1, 1],
  ["galt i halsen", "galt i halsen", "Kliche", "Erstat med original vending", 1, 1, 1],
  [
    "en ven af mig",
    "en ven af (mig|min)",
    "Anglicisme",
    "Fra det engelske 'A friend of mine'; erstat med 'en af mine venner'",
    1,
    1,
    1,
  ],
  ["gammel olding", "(gammel|gamle) olding(er)?", "Dobbeltkonfekt", "Oldinger er sjældent unge", 1, 1, 1],
  ["shampo", "shampo", "Stavefejl", "shampo -> shampoo", 1, 1, 1],
  ["foregrener", "foregrener", "Stavefejl", "foregrener -> forgrener", 1, 1, 1],
  ["prefikser", "prefiks(er)?", "Stavefejl", "prefikser -> præfikser", 1, 1, 1],
  [
    "udlænding fra andre lande",
    "udlændinge? fra ((andre lande)|(et andet land))",
    "Dobbeltkonfekt",
    "Udlændinge er per definition fra andre land",
    1,
    1,
    1,
  ],
  ["menstrutation", "menstrutation", "Stavefejl", "menstrutation -> menstruation", 1, 1, 1],
  ["Illiaden", "Illiaden", "Stavefejl", "Illiaden -> Iliaden", 0, 1, 1],
  ["Roguefort", "Roguefort", "Stavefejl", "Roguefort -> Roquefort", 1, 1, 1],
  ["spå om fremtiden", "spå(et)? om fremtiden", "Dobbeltkonfekt", "Spå", 1, 1, 1],
  ["påbudene", "påbudene", "Stavefejl", "påbudene -> påbuddene", 1, 1, 1],
  ["leguster", "leguster", "Stavefejl", "leguster -> liguster", 1, 1, 1],
];
